// ---------- perceived map: the third replay mode. What the selected observers have swept, what dimOS column carving holds, and where the patrol wants the drones next ----------
// Everything drawn here is read from episodes.<key>.view, built by pitch/perception_map.py. Nothing is simulated in the page:
// the page only replays the touched-column masks to know how long ago each column was swept.
// Shares the replay clock (rp, rpSync, rpRefresh in replay.js) and reuses scene3d.js's pure helpers (BUILD, wedge, box, cyl, normCtx, isDark, DRONE_ALT).
const pvQ = new URLSearchParams(location.search);
const PV_EXAG = 4, PV_NEVER = -9999, PV_AGE_BINS = [10, 30, 60, 120], PV_MAX_BLOCKS = 96, PV_MAX_CAND = 64, PV_TOP_NUMBERED = 3;
const pv = {src: pvQ.get('src') === 'swarm' ? 'swarm' : 'drones', prio: pvQ.get('prio') !== '0', cam: pvQ.get('cam') === 'top' ? 'top' : 'angled', force2d: pvQ.get('pv2d') === '1', on: false, mode3d: null, frame: -1, key: '', dirty: true, hover: null};
const pvEl = {view: $('#pvView'), port: $('#pvPort'), cap: $('#pvCap'), empty: $('#pvEmpty'), read: $('#pvRead'), legend: $('#pvLegend'), why: $('#pvWhy'), labels: $('#pvLabels'), hud: $('#pvHud'), scale: $('#pvScale'), bar: $('#pvBar')};
const pvCx = (site.bounds[0] + site.bounds[2]) / 2, pvCz = (site.bounds[1] + site.bounds[3]) / 2, pvW = site.bounds[2] - site.bounds[0], pvD = site.bounds[3] - site.bounds[1];
const pvNice = (id) => rpName(id);

// ---- colours: tokens only ----
let pvTok = null;
function pvCss(name, fallback){ const v = getComputedStyle(document.documentElement).getPropertyValue(name).trim(); if (!v) return fallback; normCtx.fillStyle = '#000'; normCtx.fillStyle = v; const n = normCtx.fillStyle; return n.startsWith('#') ? n : fallback; }
function pvHex(h){ return [parseInt(h.slice(1, 3), 16) / 255, parseInt(h.slice(3, 5), 16) / 255, parseInt(h.slice(5, 7), 16) / 255]; }
function pvMix(a, b, k){ const A = pvHex(a), B = pvHex(b); return '#' + [0, 1, 2].map(i => Math.round((A[i] + (B[i] - A[i]) * k) * 255).toString(16).padStart(2, '0')).join(''); }
function pvTokens(){ if (pvTok) return pvTok; const d = isDark(); const t = {ground: pvCss('--ground', d ? '#12181e' : '#f3f4f0'), surface: pvCss('--surface', d ? '#1a222a' : '#ffffff'), ink: pvCss('--ink', d ? '#eef1ee' : '#14202b'), ink2: pvCss('--ink-2', d ? '#b7c0c8' : '#44515d'), hair: pvCss('--hair', d ? '#36434f' : '#cfd4cc'), grid: pvCss('--grid', d ? '#26313b' : '#dde1da'), fence: pvCss('--fence', d ? '#aab4bd' : '#3c4650'), asset: pvCss('--asset', d ? '#eef1ee' : '#14202b'), drone: pvCss('--fleet-drone', d ? '#5598e6' : '#1f66b8'), go2: pvCss('--fleet-go2', d ? '#35c4b5' : '#0a7273'), guard: pvCss('--fleet-guard', d ? '#c3bcff' : '#2a2a78'), camera: pvCss('--fleet-camera', d ? '#7d98b3' : '#6790b5'), intruder: pvCss('--intruder', d ? '#f08a3c' : '#b84f08'), benign: pvCss('--benign', d ? '#6f767d' : '#8b8f94')};
  t.ramp = [0, 1, 2, 3, 4].map(i => pvCss('--ramp-' + i, '#6f9fcf'));
  // swept ground: fresh is the surface colour, older sweeps step toward ink. Never swept is the bare hatched ground.
  t.age = [0, 0.09, 0.18, 0.28, 0.4].map(k => pvMix(t.surface, t.ink, k));
  pvTok = t; return t; }
const pvAgeBin = (age) => age < PV_AGE_BINS[0] ? 0 : age < PV_AGE_BINS[1] ? 1 : age < PV_AGE_BINS[2] ? 2 : age < PV_AGE_BINS[3] ? 3 : 4;
const pvPrioBin = (p, pmax) => Math.max(1, Math.min(4, Math.floor(p / pmax * 5)));

// ---- payload: decode once per episode ----
const pvCache = {};
function pvBytes(s){ const bin = atob(s), out = new Uint8Array(bin.length); for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i); return out; }
function pvRuns(s){ const b = pvBytes(s), out = new Uint16Array(b.length >> 1); for (let i = 0; i < out.length; i++) out[i] = b[2 * i] | (b[2 * i + 1] << 8); return out; }
function pvData(key){ if (pvCache[key] !== undefined) return pvCache[key]; const ep = rpEps[key], v = ep && ep.view; if (!v || !v.pm) { pvCache[key] = null; return null; }
  const pm = v.pm, nCol = pm.rows * pm.cols, nCell = v.rows * v.cols, wb = pvBytes(v.w), w = new Float32Array(nCell); for (let i = 0; i < nCell; i++) w[i] = wb[i] / 255 * v.wmax;
  const d = {v, pm, nCol, nCell, w, age0: pvBytes(v.age0), swept: v.swept.map(pvRuns), touch: {drone: pm.touch.drone.map(pvRuns), ground: pm.touch.ground.map(pvRuns), fixed: pvRuns(pm.touch.fixed)}, src: {}, last: new Float32Array(nCell), lastF: -1, prio: new Float32Array(nCell), stale: new Float32Array(nCell)};
  for (const s of ['drones', 'swarm']) { const r = pm.src[s]; d.src[s] = {age0: pvBytes(r.age0), occ: r.occ, vis: r.vis, ghosts: r.ghosts, lt: new Int16Array(nCol), f: -2, known: 0, everOcc: r.occ.some(e => e[1].length)}; }
  pvCache[key] = d; return d; }
const pvAt = (list, f) => { let hit = null; for (const e of list) { if (e[0] <= f) hit = e; else break; } return hit; };
function pvApply(lt, runs, f){ for (let i = 0; i < runs.length; i += 2) lt.fill(f, runs[i], runs[i] + runs[i + 1]); }
// last-swept second per column for one source, after the frame at second f has been sensed
function pvAdvance(d, srcKey, f){ const S = d.src[srcKey]; if (f < S.f || S.f === -2) { for (let i = 0; i < d.nCol; i++) S.lt[i] = S.age0[i] === 255 ? PV_NEVER : -S.age0[i]; S.f = -1; } for (let k = S.f + 1; k <= f; k++) { pvApply(S.lt, d.touch.drone[k], k); if (srcKey === 'swarm') { pvApply(S.lt, d.touch.ground[k], k); pvApply(S.lt, d.touch.fixed, k); } } S.f = f; let known = 0; for (let i = 0; i < d.nCol; i++) if (S.lt[i] !== PV_NEVER) known++; S.known = known; }
// the patrol controller's own staleness (every observer counts) and priority = seconds stale x weight, per 5 m cell
function pvPriority(d, f){ if (f < d.lastF || d.lastF < 0) { for (let i = 0; i < d.nCell; i++) d.last[i] = d.age0[i] === 255 ? -d.v.never0 : -d.age0[i]; d.lastF = 0; } for (let k = d.lastF + 1; k <= f; k++) { const r = d.swept[k]; for (let i = 0; i < r.length; i += 2) d.last.fill(k, r[i], r[i] + r[i + 1]); } d.lastF = f; for (let i = 0; i < d.nCell; i++) { d.stale[i] = d.w[i] > 0 ? Math.max(0, f - d.last[i]) : 0; d.prio[i] = d.stale[i] * d.w[i]; } }
const pvCellXY = (d, i) => [site.bounds[0] + ((i % d.v.cols) + 0.5) * d.v.cell, site.bounds[1] + (Math.floor(i / d.v.cols) + 0.5) * d.v.cell];
const pvColXY = (d, i) => [site.bounds[0] + ((i % d.pm.cols) + 0.5) * d.pm.col, site.bounds[1] + (Math.floor(i / d.pm.cols) + 0.5) * d.pm.col];
const pvCellOf = (d, x, y) => { const c = Math.floor((x - site.bounds[0]) / d.v.cell), r = Math.floor((y - site.bounds[1]) / d.v.cell); return c < 0 || r < 0 || c >= d.v.cols || r >= d.v.rows ? -1 : r * d.v.cols + c; };

// ---- the state of one displayed second, shared by both renderers, the caption, the list and the readout ----
const pvS = {d: null, ep: null, f: 0, S: null, occ: [], vis: [], agents: [], nFresh: 0, nHeld: 0};
function pvCompute(){ const d = pvData(rp.ep), ep = rpEps[rp.ep]; pvS.d = d; pvS.ep = ep; if (!d) return; const f = Math.max(0, Math.min(d.v.n - 1, Math.floor(rp.t + 1e-6))); pvS.f = f; pvAdvance(d, pv.src, f); pvPriority(d, f); const S = pvS.S = d.src[pv.src];
  const o = pvAt(S.occ, f); pvS.occ = o ? o[1] : []; const vi = pvAt(S.vis, f); pvS.vis = vi ? vi[1] : []; pvS.nFresh = 0; pvS.nHeld = 0; for (const c of pvS.occ) { if (S.lt[c[0]] === f) pvS.nFresh++; else pvS.nHeld++; }
  pvS.agents = Object.keys(d.v.agents).sort().map(id => { const a = d.v.agents[id], tg = pvAt(a.tg, f), md = pvAt(a.md, f), cd = pvAt(a.cand, f); const mode = md ? md[1] : 0, cell = tg ? pvCellOf(d, tg[1], tg[2]) : -1, cand = cd ? cd[1] : []; const rank = cand.indexOf(cell);
    return {id, type: a.type, range: a.range, fov: a.fov, hd: a.hd[f] * Math.PI / 180, mode, tx: tg ? tg[1] : null, ty: tg ? tg[2] : null, cell, cand, rank, shown: a.type === 'drone' || pv.src === 'swarm'}; }); }

// ---- text: caption, legend, list, readout ----
function pvCaption(){ const d = pvS.d, ep = pvS.ep; if (!d) return; const S = pvS.S, who = pv.src === 'drones' ? 'the drones alone' : 'the whole swarm (drones, Go2, guard and fixed cameras)';
  const pctKnown = (S.known / d.nCol * 100).toFixed(0), g = S.ghosts[pvS.f];
  const grounded = pv.src === 'drones' && S.known === 0 ? ' Every drone was charging on its dock for the whole record, the warm-up included, so the drones alone have swept nothing and their map is blank.' : '';
  const never = grounded ? grounded : !S.everOcc ? ` In this recording ${pv.src === 'drones' ? 'no drone ever has' : 'no observer ever has'} anything standing inside its footprint, so this map stays empty of blocks${pv.src === 'drones' && d.src.swarm.everOcc ? '; switch to "Whole swarm" to see what the other observers saw' : ''}.` : '';
  pvEl.cap.innerHTML = `<b>${rpNames[rp.ep]}: what ${esc(who)} perceive, ${esc(prettyFleet(ep.fleet))}.</b> At ${pvS.f} s: <b>${pctKnown}%</b> of the map's ${d.pm.col} m columns swept at least once, <b>${pvS.occ.length}</b> occupied column${pvS.occ.length === 1 ? '' : 's'} (${pvS.nFresh} in view now, ${pvS.nHeld} remembered), <b>${g}</b> ghost${g === 1 ? '' : 's'} (remembered blocks whose object has already moved on).${never} Carving: when a column is swept again, everything stored in it is deleted and replaced by what that sweep saw, so a block stays until then; sweep history includes the ${d.v.warm} s of patrol before t = 0.`; }
function pvLegend(){ const d = pvS.d; if (!d) { pvEl.legend.innerHTML = ''; return; } const k = pvTokens(), sw = (inner) => `<svg viewBox="0 0 16 16" aria-hidden="true">${inner}</svg>`; const ramp = (cols) => `<i>${cols.map(c => `<b style="background:${c}"></b>`).join('')}</i>`;
  const items = [
    `<span class="pv-ramp">Swept ground, by seconds since the last sweep: 0 ${ramp(k.age)} ${PV_AGE_BINS[3]} or more (steps at ${PV_AGE_BINS.join(', ')} s)</span>`,
    `<span>${sw(`<rect x="1" y="1" width="14" height="14" fill="${k.ground}" stroke="${k.hair}"/><path d="M1 9L9 1M5 15L15 5M1 15L15 1" stroke="${k.hair}" stroke-width="1.2"/>`)}never swept: unknown</span>`,
    `<span>${sw(`<rect x="3" y="2" width="10" height="13" fill="${k.intruder}"/>`)}occupied column in view now, height as carved (${d.pm.vox} m voxels), drawn ${PV_EXAG} times taller</span>`,
    `<span>${sw(`<rect x="3" y="2" width="10" height="13" fill="${k.intruder}" fill-opacity=".18" stroke="${k.intruder}" stroke-dasharray="2 2"/>`)}remembered block: not swept again yet, so not carved away; labelled with its age</span>`,
    `<span>${sw(`<circle cx="8" cy="8" r="6.5" fill="${k.drone}" fill-opacity=".14" stroke="${k.drone}"/><circle cx="8" cy="8" r="2" fill="${k.drone}"/>`)}drone at 12 m and the ground it is sweeping; dimmed and flat when on its dock</span>`];
  if (pv.prio) items.push(
    `<span class="pv-ramp">Patrol priority, seconds stale x patrol weight, per ${d.v.cell} m cell: ${d.v.pmax / 5} s ${ramp(k.ramp.slice(1))} ${d.v.pmax} s or more, the 99th percentile of this episode; cells below ${d.v.pmax / 5} s are left clear</span>`,
    `<span>${sw(`<circle cx="8" cy="8" r="5.5" fill="none" stroke="${k.drone}" stroke-width="2.5"/><path d="M8 4v8M4 8h8" stroke="${k.drone}" stroke-width="1.5"/>`)}waypoint a drone is flying to</span>`,
    `<span>${sw(`<rect x="2.5" y="2.5" width="11" height="11" fill="none" stroke="${k.drone}" stroke-width="1.6"/>`)}candidate cells: the top ${(d.v.top * 100).toFixed(0)} percent of that drone's own region by priority / (1 + distance / ${d.v.d0} m); 1 to ${PV_TOP_NUMBERED} rank each drone's best</span>`);
  items.push(`<span>The intruder is drawn only while it is inside a footprint of the selected observers. ${pv.prio ? 'Priority is the patrol controller\'s own: it counts sweeps by every observer, whichever map is shown. ' : ''}Frames are synthesised from the simulator's sensor footprints (there is no real point cloud): ground points for every swept column and a stack of points where something stands. The carving itself is dimOS PackedVoxels(carve_columns=True). ${d.pm.real_frames ? 'Frames were passed as dimOS PointCloud2 messages.' : 'PointCloud2.from_numpy needs open3d, which does not load in this environment, so frames reach PackedVoxels through a minimal points_f32 stand-in.'}</span>`);
  pvEl.legend.innerHTML = items.join(''); }
let pvWhySig = '';
function pvWhy(){ const d = pvS.d; if (!d || !pv.prio) { if (pvWhySig !== '') { pvWhySig = ''; pvEl.why.innerHTML = ''; } return; } const cell = (k, v) => `<div><span class="k">${k}</span><span class="v">${v}</span></div>`;
  const rows = pvS.agents.filter(a => a.shown).map(a => { const name = esc(pvNice(a.id)); if (a.mode === 2) return `<div class="pv-row"><div class="who">${name}</div>${cell('doing', 'charging on its dock')}</div>`; if (a.mode === 1) return `<div class="pv-row"><div class="who">${name}</div>${cell('doing', 'returning to its dock')}${cell('dock at', `${a.tx.toFixed(0)} m, ${a.ty.toFixed(0)} m`)}</div>`; if (a.cell < 0) return `<div class="pv-row"><div class="who">${name}</div>${cell('doing', 'no waypoint')}</div>`;
    return `<div class="pv-row"><div class="who">${name}</div>${cell('waypoint cell', `${a.tx.toFixed(1)} m, ${a.ty.toFixed(1)} m`)}${cell('stale there', `${d.stale[a.cell].toFixed(0)} s`)}${cell('patrol weight', d.w[a.cell].toFixed(2))}${cell('priority', `${d.prio[a.cell].toFixed(0)} s`)}${cell('rank now', a.rank >= 0 ? `${a.rank + 1} of ${a.cand.length} candidates` : `outside its ${a.cand.length} candidates (chosen earlier)`)}</div>`; }).join('');
  const html = `<h3>Where each ${pv.src === 'drones' ? 'drone' : 'agent'} is heading and why</h3>${rows}`; if (html !== pvWhySig) { pvWhySig = html; pvEl.why.innerHTML = html; } }
function pvReadout(){ const d = pvS.d, h = pv.hover; if (!d) { pvEl.read.textContent = ''; return; } if (!h) { pvEl.read.textContent = 'Point at the map, or tap it, to read one column: where it is, when it was last swept, what the map holds there and its patrol priority.'; return; }
  const c = Math.floor((h[0] - site.bounds[0]) / d.pm.col), r = Math.floor((h[1] - site.bounds[1]) / d.pm.col); if (c < 0 || r < 0 || c >= d.pm.cols || r >= d.pm.rows) { pvEl.read.textContent = 'Outside the map.'; return; } const i = r * d.pm.cols + c, [x, y] = pvColXY(d, i), lt = pvS.S.lt[i], occ = pvS.occ.find(o => o[0] === i), ci = pvCellOf(d, x, y);
  const state = lt === PV_NEVER ? 'never swept, unknown' : occ ? `${lt === pvS.f ? 'occupied, in view now' : 'remembered block, not yet carved'}, carved to ${((occ[1] + 1) * d.pm.vox).toFixed(2)} m` : 'free ground';
  pvEl.read.textContent = `Column at ${x.toFixed(1)} m east, ${y.toFixed(1)} m north: ${lt === PV_NEVER ? 'not swept in this record' : lt === pvS.f ? 'being swept now' : `last swept ${pvS.f - lt} s ago`}; ${state}. Patrol cell here: ${ci < 0 ? 'none' : `${d.stale[ci].toFixed(0)} s stale, weight ${d.w[ci].toFixed(2)}, priority ${d.prio[ci].toFixed(0)} s`}.`; }

// ---- labels over either renderer: fixed-size HTML, greedy placement ----
const pvLabels = [];
function pvLabel(cls, prio){ const el = document.createElement('div'); el.className = 'pv-label' + (cls ? ' ' + cls : ''); el.style.visibility = 'hidden'; pvEl.labels.appendChild(el); const L = {el, prio, text: '', on: false, ax: 0, ay: 0, r: 8, w: 0, h: 14, shown: false, x: -1, y: -1}; pvLabels.push(L); pvLabels.sort((a, b) => a.prio - b.prio); return L; }
function pvSetLabel(L, text, ax, ay, r){ if (text !== L.text) { L.text = text; L.el.textContent = text; L.w = 0; } L.on = !!text; L.ax = ax; L.ay = ay; L.r = r == null ? 8 : r; }
const pvPool = {agent: {}, way: {}, num: [], ghost: [], site: [], intruder: null};
function pvPoolGet(kind, key, cls, prio){ const p = pvPool[kind]; if (Array.isArray(p)) { while (p.length <= key) p.push(pvLabel(cls, prio)); return p[key]; } return p[key] || (p[key] = pvLabel(cls, prio)); }
function pvPlaceLabels(){ const W = pvEl.port.clientWidth, H = pvEl.port.clientHeight, taken = [[0, 0, Math.min(W, pvEl.hud.offsetWidth + 12), pvEl.hud.offsetHeight + 10], [0, H - 34, 130, 34]];
  const hit = (x, y, w, h) => taken.some(q => x < q[0] + q[2] && q[0] < x + w && y < q[1] + q[3] && q[1] < y + h);
  for (const L of pvLabels) if (L.on && L.r > 3) taken.push([L.ax - L.r, L.ay - L.r, 2 * L.r, 2 * L.r]);
  for (const L of pvLabels) { let ok = false, x = 0, y = 0; if (L.on && L.ax > -10 && L.ax < W + 10 && L.ay > -10 && L.ay < H + 10) { if (!L.w) { L.w = L.el.offsetWidth; L.h = L.el.offsetHeight || 14; } const c = [[L.ax - L.w / 2, L.ay - L.r - L.h - 3], [L.ax + L.r + 4, L.ay - L.h / 2], [L.ax - L.r - 4 - L.w, L.ay - L.h / 2], [L.ax - L.w / 2, L.ay + L.r + 5], [L.ax + L.r + 2, L.ay - L.r - L.h - 8], [L.ax - L.r - 2 - L.w, L.ay + L.r + 8]]; if (L.r <= 3) c.unshift([L.ax - L.w / 2, L.ay - L.h / 2]); for (const q of c) { if (q[0] >= 2 && q[1] >= 2 && q[0] + L.w <= W - 2 && q[1] + L.h <= H - 2 && !hit(q[0], q[1], L.w, L.h)) { ok = true; x = Math.round(q[0]); y = Math.round(q[1]); break; } } }
    if (ok) { taken.push([x - 2, y - 1, L.w + 4, L.h + 2]); if (x !== L.x || y !== L.y) { L.x = x; L.y = y; L.el.style.transform = `translate(${x}px,${y}px)`; } if (!L.shown) { L.shown = true; L.el.style.visibility = 'visible'; } } else if (L.shown) { L.shown = false; L.el.style.visibility = 'hidden'; } } }
// one pass that names every label from the state; project(x, y, height) gives port pixels
function pvNameLabels(project){ const d = pvS.d, narrow = pvEl.port.clientWidth < 560; for (const L of pvLabels) L.on = false; pvNumN = 0; if (!d) return; const t = rp.t, ep = pvS.ep; let p;
  pvS.agents.forEach(a => { const tr = ep.tracks[a.id]; if (!tr) return; const q = positionAt(tr, t), up = a.type === 'drone' && a.mode !== 2 ? DRONE_ALT : 2; p = project(q[1], q[2], up); pvSetLabel(pvPoolGet('agent', a.id, a.shown ? '' : 'quiet', a.type === 'drone' ? 1 : 3), pvNice(a.id) + (a.mode === 2 ? ', docked' : a.mode === 1 ? ', returning' : ''), p[0], p[1], 10);
    if (pv.prio && a.shown && a.mode === 0 && a.tx != null) { p = project(a.tx, a.ty, 0); pvSetLabel(pvPoolGet('way', a.id, 'quiet', 2), `${pvNice(a.id)} heading here`, p[0], p[1], 8); if (a.type === 'drone') a.cand.slice(0, PV_TOP_NUMBERED).forEach((c, i) => { if (c === a.cell) return; const [x, y] = pvCellXY(d, c); p = project(x, y, 0); pvSetLabel(pvPoolGet('num', pvNumN++, 'num', 5), String(i + 1), p[0], p[1], 2); }); } });
  if (pvS.vis.includes('intruder') && ep.tracks.intruder) { const q = positionAt(ep.tracks.intruder, t); p = project(q[1], q[2], 3 * PV_EXAG); pvSetLabel(pvPool.intruder || (pvPool.intruder = pvLabel('warm', 0)), `intruder, in view of ${pv.src === 'drones' ? 'a drone' : 'the swarm'}`, p[0], p[1], 9); }
  let g = 0; for (const o of pvS.occ) { const lt = pvS.S.lt[o[0]]; if (lt === pvS.f) continue; const [x, y] = pvColXY(d, o[0]); p = project(x, y, (o[1] + 1) * d.pm.vox * PV_EXAG); pvSetLabel(pvPoolGet('ghost', g++, 'warm', 2), `seen ${pvS.f - lt} s ago, not swept since`, p[0], p[1], 6); }
  let s = 0; p = project(site.asset.x, site.asset.y, 3); pvSetLabel(pvPoolGet('site', s++, 'quiet', 6), 'asset', p[0], p[1], 8); if (!narrow) site.entry_points.forEach(e => { p = project(e.position.x, e.position.y, 0); pvSetLabel(pvPoolGet('site', s++, 'quiet', 7), rpPlace(e.id), p[0], p[1], 6); }); }
let pvNumN = 0;

// ---- 3D renderer (three.js r128, same library and projection as the Map) ----
const p3 = {ready: false, renderer: null, scene: null, camera: null, mats: [], tiles: null, heat: null, blocks: null, ghosts: null, ghostEdges: [], agents: {}, cams: [], cand: {}, hatch: null, raf: 0, last: 0, vec: null, ray: null, plane: null, hit: null, col: null, tileOn: null, heatOn: null, intruder: null};
const pvCam = {cur: {tx: 0, tz: 0, th: Math.PI / 2, ph: 0.66, h: 80}, goal: {tx: 0, tz: 0, th: Math.PI / 2, ph: 0.66, h: 80}, aspect: 1.6, viewH: 400, fitted: true, preset: 'angled', dragging: false, appliedH: -1, appliedA: -1, glyph: 1};
const PV_CAM_R = 900, PV_PHI_MIN = 0.002, PV_PHI_MAX = 1.25;
function pvLoadThree(done, fail){ if (window.THREE) { done(); return; } let sc = document.querySelector('script[src*="three.min.js"]'); if (!sc) { sc = document.createElement('script'); sc.src = 'https://cdnjs.cloudflare.com/ajax/libs/three.js/r128/three.min.js'; document.head.appendChild(sc); } sc.addEventListener('load', () => (window.THREE ? done() : fail())); sc.addEventListener('error', fail); }
function pvMat(tok, opts){ const o = opts || {}, M = o.lit ? THREE.MeshLambertMaterial : THREE.MeshBasicMaterial; const m = new M({color: tok ? pvTokens()[tok] : 0xffffff, transparent: o.opacity != null, opacity: o.opacity == null ? 1 : o.opacity, depthWrite: o.opacity == null, side: THREE.DoubleSide}); if (tok) p3.mats.push([m, tok]); return m; }
function pvLineMat(tok, opacity){ const m = new THREE.LineBasicMaterial({color: pvTokens()[tok], transparent: opacity != null, opacity: opacity == null ? 1 : opacity, depthWrite: false}); p3.mats.push([m, tok]); return m; }
function pvLines(pts, material, loop){ const g = new THREE.BufferGeometry(); g.setAttribute('position', new THREE.Float32BufferAttribute(pts, 3)); const l = loop ? new THREE.LineLoop(g, material) : new THREE.LineSegments(g, material); l.frustumCulled = false; l.renderOrder = 3; return l; }
function pvHatch(){ const k = pvTokens(), c = document.createElement('canvas'); c.width = c.height = 32; const g = c.getContext('2d'); g.fillStyle = k.ground; g.fillRect(0, 0, 32, 32); g.strokeStyle = k.hair; g.lineWidth = 2; g.beginPath(); for (let i = -32; i <= 64; i += 16) { g.moveTo(i, 32); g.lineTo(i + 32, 0); } g.stroke(); return c; }
function pvFlat(size){ const g = new THREE.PlaneGeometry(size, size); g.rotateX(-Math.PI / 2); return g; }
function pvInstanced(geometry, material, n, y){ const m = new THREE.InstancedMesh(geometry, material, n); m.frustumCulled = false; const a = m.instanceMatrix.array; a.fill(0); for (let i = 0; i < n; i++) { a[i * 16 + 13] = y; a[i * 16 + 15] = 1; } m.setColorAt(0, new THREE.Color(1, 1, 1)); m.instanceColor.array.fill(1); return m; }
function pvSetInst(mesh, i, X, Z, sx, sy){ const a = mesh.instanceMatrix.array, o = i * 16; a[o] = sx; a[o + 5] = sy; a[o + 10] = sx; a[o + 12] = X; a[o + 14] = Z; }
function pvSetCol(mesh, i, rgb){ const a = mesh.instanceColor.array; a[i * 3] = rgb[0]; a[i * 3 + 1] = rgb[1]; a[i * 3 + 2] = rgb[2]; }

function pvInit3D(){ const k = pvTokens(), [x0, y0, x1, y1] = site.bounds;
  const r = p3.renderer = new THREE.WebGLRenderer({antialias: true, powerPreference: 'low-power'}); r.setPixelRatio(Math.min(window.devicePixelRatio || 1, 2)); pvEl.port.insertBefore(r.domElement, pvEl.port.firstChild);
  const sc = p3.scene = new THREE.Scene(); sc.background = new THREE.Color(k.ground); p3.camera = new THREE.OrthographicCamera(-100, 100, 60, -60, 1, 3000); p3.vec = new THREE.Vector3(); p3.ray = new THREE.Raycaster(); p3.plane = new THREE.Plane(new THREE.Vector3(0, 1, 0), 0); p3.hit = new THREE.Vector3(); p3.ndc = new THREE.Vector2();
  sc.add(new THREE.HemisphereLight(0xffffff, 0xbfc4d6, 0.9)); const sun = new THREE.DirectionalLight(0xffffff, 0.35); sun.position.set(-60, 200, 90); sc.add(sun);
  // unknown ground: hatched, so never swept reads as unknown and not as empty
  p3.hatch = new THREE.CanvasTexture(pvHatch()); p3.hatch.wrapS = p3.hatch.wrapT = THREE.RepeatWrapping; p3.hatch.repeat.set(pvW / 10, pvD / 10); const gm = new THREE.Mesh(new THREE.PlaneGeometry(pvW, pvD), new THREE.MeshBasicMaterial({map: p3.hatch})); gm.rotation.x = -Math.PI / 2; gm.position.y = -0.05; sc.add(gm);
  // quiet orientation: 50 m grid, fence, entries, docks, asset
  const grid = []; for (let x = Math.ceil(x0 / 50) * 50; x <= x1; x += 50) grid.push(x - pvCx, 0.06, -(y0 - pvCz), x - pvCx, 0.06, -(y1 - pvCz)); for (let y = Math.ceil(y0 / 50) * 50; y <= y1; y += 50) grid.push(x0 - pvCx, 0.06, -(y - pvCz), x1 - pvCx, 0.06, -(y - pvCz)); sc.add(pvLines(grid, pvLineMat('ink2', 0.35)));
  const per = []; site.perimeter.forEach(p => per.push(p.x - pvCx, 0.08, -(p.y - pvCz))); sc.add(pvLines(per, pvLineMat('fence'), true));
  const wallMat = pvMat('fence', {opacity: 0.16}); site.perimeter.forEach((a, i) => { const b = site.perimeter[(i + 1) % site.perimeter.length], len = Math.hypot(b.x - a.x, b.y - a.y); const w = new THREE.Mesh(new THREE.PlaneGeometry(len, 2), wallMat); w.position.set((a.x + b.x) / 2 - pvCx, 1, -((a.y + b.y) / 2 - pvCz)); w.rotation.y = Math.atan2(b.y - a.y, b.x - a.x); sc.add(w); });
  const sq = (x, y, h, out) => { const X = x - pvCx, Z = -(y - pvCz); out.push(X - h, 0.1, Z - h, X + h, 0.1, Z - h, X + h, 0.1, Z - h, X + h, 0.1, Z + h, X + h, 0.1, Z + h, X - h, 0.1, Z + h, X - h, 0.1, Z + h, X - h, 0.1, Z - h); };
  const marks = []; site.entry_points.forEach(e => sq(e.position.x, e.position.y, 2.5, marks)); site.docks.forEach(dk => sq(dk.position.x, dk.position.y, 1.6, marks)); sc.add(pvLines(marks, pvLineMat('fence')));
  const asset = box(12, 3, 9, pvMat('asset', {lit: true}), site.asset.x - pvCx, 1.5, -(site.asset.y - pvCz)); sc.add(asset);
  // fixed cameras: a quiet post always, the wedge only when the whole swarm feeds the map
  site.fixed_sensors.forEach(s => { const c = D.curves[s.sensor_type] || {fov_deg: 60, range: 30}, g = BUILD.camera(pvMat('camera', {lit: true})), a = s.heading_deg * Math.PI / 180; g.position.set(s.position.x - pvCx, 0, -(s.position.y - pvCz)); g.rotation.y = a; sc.add(g); const w = wedge(c.range, c.fov_deg, pvMat('camera', {opacity: 0.12})); w.position.set(s.position.x - pvCx, 0.12, -(s.position.y - pvCz)); w.rotation.y = a; sc.add(w); p3.cams.push({g, w}); });
  p3.ready = true; }

// everything that depends on the episode's grid sizes: built once per episode, then only recoloured
function pvBuildEpisode(key){ const d = pvData(key), sc = p3.scene, root = new THREE.Group(); sc.add(root); const E = p3.eps[key] = {root, agents: {}, tileOn: new Uint8Array(d.nCol), heatOn: new Uint8Array(d.nCell)};
  E.tiles = pvInstanced(pvFlat(d.pm.col * 0.94), pvMat(null), d.nCol, 0.02); E.tiles.renderOrder = 1; root.add(E.tiles);
  E.heat = pvInstanced(pvFlat(d.v.cell * 0.8), pvMat(null, {opacity: 0.72}), d.nCell, 0.3); E.heat.renderOrder = 2; root.add(E.heat);
  const bg = new THREE.BoxGeometry(1, 1, 1); bg.translate(0, 0.5, 0); E.blocks = pvInstanced(bg, pvMat(null, {lit: true}), PV_MAX_BLOCKS, 0); E.ghosts = pvInstanced(bg, pvMat(null, {opacity: 0.2}), PV_MAX_BLOCKS, 0); E.ghosts.renderOrder = 4; root.add(E.blocks, E.ghosts);
  const eg = new THREE.EdgesGeometry(bg); E.edges = Array.from({length: 24}, () => { const l = new THREE.LineSegments(eg, pvLineMat('intruder')); l.visible = false; l.renderOrder = 5; root.add(l); return l; });
  Object.keys(d.v.agents).sort().forEach(id => { const a = d.v.agents[id], kind = a.type === 'drone' ? 'drone' : a.type === 'go2' ? 'go2' : 'guard'; const A = E.agents[id] = {kind, solid: pvMat(kind, {lit: true}), dim: pvMat(kind, {lit: true, opacity: 0.4}), docked: null};
    A.glyph = (BUILD[kind] || BUILD.guard)(A.solid); root.add(A.glyph);
    A.cover = wedge(a.range, a.fov, pvMat(kind, {opacity: 0.13})); A.cover.renderOrder = 3; root.add(A.cover);
    const ring = [], f = Math.min(360, a.fov) * Math.PI / 180, n = 48; if (a.fov < 360) ring.push(0, 0, 0); for (let j = 0; j <= n; j++) { const an = -f / 2 + f * j / n; ring.push(a.range * Math.cos(an), 0, -a.range * Math.sin(an)); } A.edge = pvLines(ring, pvLineMat(kind, 0.7), true); root.add(A.edge);
    if (kind === 'drone') { A.drop = cyl(0.08, 0.08, 1, A.dim, 0, 0, 0, 6); root.add(A.drop); }
    const wg = new THREE.RingGeometry(1.5, 2.3, 24); wg.rotateX(-Math.PI / 2); A.way = new THREE.Mesh(wg, pvMat(kind)); A.way.position.y = 0.5; A.way.renderOrder = 6; root.add(A.way);
    A.line = box(1, 0.05, 1, pvMat(kind), 0, 0.5, 0); A.line.renderOrder = 6; root.add(A.line);
    const fg = new THREE.RingGeometry(d.v.cell * 0.5 * Math.SQRT2 - 0.75, d.v.cell * 0.5 * Math.SQRT2 - 0.1, 4, 1, Math.PI / 4); fg.rotateX(-Math.PI / 2); A.candLines = pvInstanced(fg, pvMat(kind), PV_MAX_CAND, 0.55); A.candLines.renderOrder = 5; A.candLines.count = 0; root.add(A.candLines); });
  E.intruder = BUILD.intruder(pvMat('intruder', {lit: true})); E.intruder.visible = false; root.add(E.intruder); return E; }
p3.eps = {};

function pvUpdateMap3D(){ const d = pvS.d, E = p3.eps[rp.ep] || pvBuildEpisode(rp.ep), k = pvTokens(), S = pvS.S, f = pvS.f; for (const key of Object.keys(p3.eps)) p3.eps[key].root.visible = key === rp.ep;
  const age = k.age.map(pvHex), ramp = k.ramp.map(pvHex), hot = pvHex(k.intruder);
  for (let i = 0; i < d.nCol; i++) { const lt = S.lt[i], on = lt !== PV_NEVER ? 1 : 0; if (on !== E.tileOn[i]) { E.tileOn[i] = on; const [x, y] = pvColXY(d, i); pvSetInst(E.tiles, i, x - pvCx, -(y - pvCz), on, on); } if (on) pvSetCol(E.tiles, i, age[pvAgeBin(f - lt)]); }
  E.tiles.instanceMatrix.needsUpdate = true; E.tiles.instanceColor.needsUpdate = true;
  E.heat.visible = pv.prio; if (pv.prio) { const floor = d.v.pmax / 5; for (let i = 0; i < d.nCell; i++) { const on = d.prio[i] > floor ? 1 : 0; if (on !== E.heatOn[i]) { E.heatOn[i] = on; const [x, y] = pvCellXY(d, i); pvSetInst(E.heat, i, x - pvCx, -(y - pvCz), on, on); } if (on) pvSetCol(E.heat, i, ramp[pvPrioBin(d.prio[i], d.v.pmax)]); } E.heat.instanceMatrix.needsUpdate = true; E.heat.instanceColor.needsUpdate = true; }
  let nb = 0, ng = 0; for (const e of E.edges) e.visible = false; for (const o of pvS.occ) { const [x, y] = pvColXY(d, o[0]), h = (o[1] + 1) * d.pm.vox * PV_EXAG, fresh = S.lt[o[0]] === f, mesh = fresh ? E.blocks : E.ghosts, n = fresh ? nb++ : ng++; if (n >= PV_MAX_BLOCKS) continue; pvSetInst(mesh, n, x - pvCx, -(y - pvCz), d.pm.col * 0.94, h); mesh.instanceMatrix.array[n * 16 + 13] = 0.03; pvSetCol(mesh, n, hot); if (!fresh && ng <= E.edges.length) { const e = E.edges[ng - 1]; e.visible = true; e.position.set(x - pvCx, 0.03, -(y - pvCz)); e.scale.set(d.pm.col * 0.94, h, d.pm.col * 0.94); } }
  E.blocks.count = Math.min(nb, PV_MAX_BLOCKS); E.ghosts.count = Math.min(ng, PV_MAX_BLOCKS); E.blocks.instanceMatrix.needsUpdate = E.ghosts.instanceMatrix.needsUpdate = true; E.blocks.instanceColor.needsUpdate = E.ghosts.instanceColor.needsUpdate = true;
  p3.cams.forEach(c => { c.w.visible = pv.src === 'swarm'; });
  // candidate outlines change only with the second
  pvS.agents.forEach(a => { const A = E.agents[a.id]; if (!A) return; const show = pv.prio && a.shown && a.mode === 0 && a.type === 'drone'; A.candLines.visible = show; if (!show) return; const n = Math.min(a.cand.length, PV_MAX_CAND); for (let j = 0; j < n; j++) { const [x, y] = pvCellXY(d, a.cand[j]); pvSetInst(A.candLines, j, x - pvCx, -(y - pvCz), 1, 1); } A.candLines.count = n; A.candLines.instanceMatrix.needsUpdate = true; }); }

// agents move with the continuous clock; the map layers above only with the whole second
function pvUpdateActors3D(){ const E = p3.eps[rp.ep]; if (!E) return; const ep = pvS.ep, t = rp.t, gs = pvCam.glyph;
  pvS.agents.forEach(a => { const A = E.agents[a.id], tr = ep.tracks[a.id]; if (!A || !tr) return; const q = positionAt(tr, t), X = q[1] - pvCx, Z = -(q[2] - pvCz), docked = a.mode === 2;
    if (docked !== A.docked) { A.docked = docked; const m = docked ? A.dim : A.solid; A.glyph.traverse(c => { if (c.isMesh) c.material = m; }); }
    A.glyph.scale.set(gs, gs, gs); A.glyph.position.set(X, a.type === 'drone' && !docked ? DRONE_ALT : (docked ? 0.3 : 0), Z); A.glyph.rotation.y = a.type === 'drone' ? 0 : a.hd;
    const sensing = !docked && a.shown; A.cover.visible = A.edge.visible = sensing; if (sensing) { A.cover.position.set(X, 0.14, Z); A.cover.rotation.y = a.hd; A.edge.position.set(X, 0.16, Z); A.edge.rotation.y = a.hd; }
    if (A.drop) { A.drop.visible = !docked; A.drop.position.set(X, DRONE_ALT / 2, Z); A.drop.scale.set(gs * 1.6, DRONE_ALT, gs * 1.6); }
    const way = pv.prio && a.shown && a.mode === 0 && a.tx != null; A.way.visible = A.line.visible = way; if (way) { const WX = a.tx - pvCx, WZ = -(a.ty - pvCz); A.way.position.x = WX; A.way.position.z = WZ; A.way.scale.set(Math.max(1, gs * 0.8), 1, Math.max(1, gs * 0.8)); const len = Math.hypot(WX - X, WZ - Z) || 0.01; A.line.position.set((X + WX) / 2, 0.5, (Z + WZ) / 2); A.line.rotation.y = -Math.atan2(WZ - Z, WX - X); A.line.scale.set(len, 1, Math.max(0.5, gs * 0.22)); } });
  const seen = pvS.vis.includes('intruder') && ep.tracks.intruder; E.intruder.visible = !!seen; if (seen) { const q = positionAt(ep.tracks.intruder, t); E.intruder.position.set(q[1] - pvCx, 2.6 * PV_EXAG, -(q[2] - pvCz)); E.intruder.scale.set(gs, gs, gs); } }

// camera: the Map's damped orthographic orbit and its presets, on this viewport
function pvFit(th, ph){ let u0 = 1e9, u1 = -1e9, r0 = 1e9, r1 = -1e9; for (const sx of [-1, 1]) for (const sz of [-1, 1]) for (const Y of [0, DRONE_ALT + 3]) { const X = sx * pvW / 2, Z = sz * pvD / 2, r = X * Math.sin(th) - Z * Math.cos(th), u = -X * Math.cos(ph) * Math.cos(th) + Y * Math.sin(ph) - Z * Math.cos(ph) * Math.sin(th); r0 = Math.min(r0, r); r1 = Math.max(r1, r); u0 = Math.min(u0, u); u1 = Math.max(u1, u); } const padTop = 2 * 40 / pvCam.viewH, h = Math.max((u1 - u0) / 2 / (0.92 - padTop / 2), (r1 - r0) / 2 / pvCam.aspect / 0.94), uc = (u0 + u1) / 2 + h * padTop / 2, rc = (r0 + r1) / 2, cp = Math.max(0.2, Math.cos(ph)); return {h, tx: Math.sin(th) * rc - Math.cos(th) * uc / cp, tz: -Math.cos(th) * rc - Math.sin(th) * uc / cp}; }
function pvApplyFit(){ const f = pvFit(pvCam.goal.th, pvCam.goal.ph); Object.assign(pvCam.goal, f); }
function pvPreset(name, snap){ const g = pvCam.goal; pvCam.preset = name; pvCam.fitted = true; if (name === 'top') { g.th = Math.PI / 2; g.ph = PV_PHI_MIN; } else if (name === 'angled') { g.th = Math.PI / 2 + 0.12; g.ph = 0.66; } pvApplyFit(); const dth = g.th - pvCam.cur.th; if (Math.abs(dth) > Math.PI) pvCam.cur.th += Math.sign(dth) * 2 * Math.PI; if (snap || rpReduced.matches) Object.assign(pvCam.cur, g); pvSyncHud(); pvRequest(); }
function pvSyncHud(){ pvEl.hud.querySelectorAll('button[data-cam]').forEach(b => { if (b.dataset.cam === 'top' || b.dataset.cam === 'angled') b.setAttribute('aria-pressed', String(b.dataset.cam === pvCam.preset)); }); }
function pvStepCamera(dt){ const c = pvCam.cur, g = pvCam.goal, k = rpReduced.matches ? 1 : 1 - Math.exp(-dt * 11); let moving = false; for (const f of ['tx', 'tz', 'th', 'ph']) { const dlt = g[f] - c[f]; if (Math.abs(dlt) > (f === 'tx' || f === 'tz' ? 0.02 : 0.0004)) { c[f] += dlt * k; moving = true; } else c[f] = g[f]; } const dh = Math.log(g.h / c.h); if (Math.abs(dh) > 0.001) { c.h *= Math.exp(dh * k); moving = true; } else c.h = g.h;
  const sp = Math.sin(c.ph), cp = Math.cos(c.ph), cam = p3.camera; cam.position.set(c.tx + PV_CAM_R * sp * Math.cos(c.th), PV_CAM_R * cp, c.tz + PV_CAM_R * sp * Math.sin(c.th)); cam.lookAt(c.tx, 0, c.tz);
  if (c.h !== pvCam.appliedH || pvCam.aspect !== pvCam.appliedA) { pvCam.appliedH = c.h; pvCam.appliedA = pvCam.aspect; cam.top = c.h; cam.bottom = -c.h; cam.left = -c.h * pvCam.aspect; cam.right = c.h * pvCam.aspect; cam.updateProjectionMatrix(); const mpp = 2 * c.h / pvCam.viewH; pvCam.glyph = Math.max(0.8, Math.min(4.2, mpp * 7.5)); let nice = 1; for (const v of [1, 2, 5, 10, 20, 50, 100]) if (v <= 110 * mpp) nice = v; pvEl.scale.hidden = false; pvEl.scale.firstElementChild.textContent = `${nice} m`; pvEl.scale.lastElementChild.style.width = (nice / mpp).toFixed(1) + 'px'; }
  cam.updateMatrixWorld(); return moving; }
function pvShift(a, b){ const g = pvCam.goal, cp = Math.max(0.2, Math.cos(g.ph)); g.tx = Math.max(-pvW / 2 - 20, Math.min(pvW / 2 + 20, g.tx + Math.sin(g.th) * a - Math.cos(g.th) * b / cp)); g.tz = Math.max(-pvD / 2 - 20, Math.min(pvD / 2 + 20, g.tz - Math.cos(g.th) * a - Math.sin(g.th) * b / cp)); }
function pvZoom(factor, clientX, clientY){ const r = pvEl.port.getBoundingClientRect(), nx = clientX == null ? 0 : ((clientX - r.left) / r.width) * 2 - 1, ny = clientY == null ? 0 : -(((clientY - r.top) / r.height) * 2 - 1), g = pvCam.goal, h0 = g.h, h1 = Math.max(10, Math.min(pvFit(g.th, g.ph).h * 1.6, h0 * factor)); g.h = h1; pvShift(nx * pvCam.aspect * (h0 - h1), ny * (h0 - h1)); pvCam.fitted = false; pvCam.preset = ''; pvSyncHud(); pvRequest(); }
function pvProject3D(x, y, up){ const v = p3.vec.set(x - pvCx, up, -(y - pvCz)).project(p3.camera); return [(v.x + 1) / 2 * pvEl.port.clientWidth, (1 - v.y) / 2 * pvEl.port.clientHeight]; }
function pvPick3D(clientX, clientY){ const r = pvEl.port.getBoundingClientRect(); p3.ndc.set(((clientX - r.left) / r.width) * 2 - 1, -(((clientY - r.top) / r.height) * 2 - 1)); p3.ray.setFromCamera(p3.ndc, p3.camera); return p3.ray.ray.intersectPlane(p3.plane, p3.hit) ? [p3.hit.x + pvCx, pvCz - p3.hit.z] : null; }
function pvResize3D(){ const w = pvEl.port.clientWidth, h = pvEl.port.clientHeight; if (w < 10 || h < 10) return; p3.renderer.setSize(w, h, false); pvCam.aspect = w / h; pvCam.viewH = h; if (pvCam.fitted) { pvApplyFit(); Object.assign(pvCam.cur, pvCam.goal); } pvCam.appliedH = -1; for (const L of pvLabels) L.w = 0; }

// ---- 2D renderer: the same layers on a plain canvas, when WebGL or three.js is not there ----
const p2 = {canvas: null, w: 0, h: 0, dpr: 1, P: null, s: 1};
function pvInit2D(why){ const c = p2.canvas = document.createElement('canvas'); pvEl.port.insertBefore(c, pvEl.port.firstChild); pvEl.hud.hidden = true; pvEl.port.style.cursor = 'crosshair'; pv.why2d = why; }
function pvResize2D(){ const w = pvEl.port.clientWidth, h = pvEl.port.clientHeight; if (w < 10 || h < 10) return; const dpr = Math.min(window.devicePixelRatio || 1, 3); p2.canvas.width = Math.round(w * dpr); p2.canvas.height = Math.round(h * dpr); p2.w = w; p2.h = h; p2.dpr = dpr; const G = rpGeom(w, h); p2.P = G.P; p2.s = G.s; for (const L of pvLabels) L.w = 0; }
function pvDraw2D(){ const d = pvS.d; if (!d || !p2.P) return; const g = p2.canvas.getContext('2d'), k = pvTokens(), P = p2.P, s = p2.s, S = pvS.S, f = pvS.f, ep = pvS.ep, t = rp.t; g.setTransform(p2.dpr, 0, 0, p2.dpr, 0, 0);
  const hatch = g.createPattern(pvHatch(), 'repeat'); const [gx0, gy1] = P(site.bounds[0], site.bounds[3]), [gx1, gy0] = P(site.bounds[2], site.bounds[1]); g.fillStyle = k.ground; g.fillRect(0, 0, p2.w, p2.h); g.fillStyle = hatch; g.fillRect(gx0, gy1, gx1 - gx0, gy0 - gy1);
  const cs = d.pm.col * s; for (let i = 0; i < d.nCol; i++) { const lt = S.lt[i]; if (lt === PV_NEVER) continue; const [x, y] = pvColXY(d, i), [px, py] = P(x, y); g.fillStyle = k.age[pvAgeBin(f - lt)]; g.fillRect(px - cs / 2, py - cs / 2, cs * 0.94, cs * 0.94); }
  if (pv.prio) { const hs = d.v.cell * s * 0.8, floor = d.v.pmax / 5; g.globalAlpha = 0.72; for (let i = 0; i < d.nCell; i++) { if (d.prio[i] <= floor) continue; const [x, y] = pvCellXY(d, i), [px, py] = P(x, y); g.fillStyle = k.ramp[pvPrioBin(d.prio[i], d.v.pmax)]; g.fillRect(px - hs / 2, py - hs / 2, hs, hs); } g.globalAlpha = 1; }
  g.strokeStyle = k.fence; g.lineWidth = 2; g.beginPath(); site.perimeter.forEach((p, i) => { const [x, y] = P(p.x, p.y); i ? g.lineTo(x, y) : g.moveTo(x, y); }); g.closePath(); g.stroke(); g.lineWidth = 1.5; site.entry_points.forEach(e => { const [x, y] = P(e.position.x, e.position.y); g.strokeRect(x - 5, y - 5, 10, 10); }); site.docks.forEach(dk => { const [x, y] = P(dk.position.x, dk.position.y); g.strokeRect(x - 3, y - 3, 6, 6); }); const [ax, ay] = P(site.asset.x, site.asset.y); g.fillStyle = k.asset; g.fillRect(ax - 6, ay - 6, 12, 12);
  for (const o of pvS.occ) { const [x, y] = pvColXY(d, o[0]), [px, py] = P(x, y), q = Math.max(cs, 7), fresh = S.lt[o[0]] === f; g.strokeStyle = g.fillStyle = k.intruder; g.lineWidth = 1.5; if (fresh) g.fillRect(px - q / 2, py - q / 2, q, q); else { g.globalAlpha = 0.2; g.fillRect(px - q / 2, py - q / 2, q, q); g.globalAlpha = 1; g.setLineDash([2, 2]); g.strokeRect(px - q / 2, py - q / 2, q, q); g.setLineDash([]); } }
  pvS.agents.forEach(a => { const tr = ep.tracks[a.id]; if (!tr) return; const q = positionAt(tr, t), [x, y] = P(q[1], q[2]), col = k[a.type] || k.drone, docked = a.mode === 2; g.strokeStyle = g.fillStyle = col;
    if (!docked && a.shown) { const h = -a.hd, fv = Math.min(360, a.fov) * Math.PI / 360; g.beginPath(); if (a.fov < 360) g.moveTo(x, y); g.arc(x, y, a.range * s, h - fv, h + fv); g.closePath(); g.globalAlpha = 0.13; g.fill(); g.globalAlpha = 0.7; g.lineWidth = 1; g.stroke(); g.globalAlpha = 1; }
    if (pv.prio && a.shown && a.mode === 0 && a.tx != null) { const [wx, wy] = P(a.tx, a.ty); g.lineWidth = 1.5; g.beginPath(); g.moveTo(x, y); g.lineTo(wx, wy); g.stroke(); g.lineWidth = 2.5; g.beginPath(); g.arc(wx, wy, 5.5, 0, 7); g.stroke(); if (a.type === 'drone') { g.lineWidth = 1.5; const hc = d.v.cell * s - 3; a.cand.forEach(c => { const [cx2, cy2] = pvCellXY(d, c), [qx, qy] = P(cx2, cy2); g.strokeRect(qx - hc / 2, qy - hc / 2, hc, hc); }); } }
    rpShape(g, a.type, x, y, 5); if (docked) { g.fillStyle = k.surface; g.fill(); g.lineWidth = 2; g.stroke(); } else g.fill(); });
  if (pvS.vis.includes('intruder') && ep.tracks.intruder) { const q = positionAt(ep.tracks.intruder, t), [x, y] = P(q[1], q[2]); rpShape(g, 'intruder', x, y, 5); g.fillStyle = k.intruder; g.fill(); } }
const pvProject2D = (x, y) => p2.P(x, y);
function pvPick2D(clientX, clientY){ const r = pvEl.port.getBoundingClientRect(), o = p2.P(site.bounds[0], site.bounds[3]); return [site.bounds[0] + (clientX - r.left - o[0]) / p2.s, site.bounds[3] - (clientY - r.top - o[1]) / p2.s]; }

// ---- render on demand; continuous only while the camera is moving or being dragged (playback arrives through sync) ----
function pvRequest(){ if (!pv.on || p3.raf) return; p3.raf = requestAnimationFrame(pvTick); }
function pvTick(now){ p3.raf = 0; if (!pv.on || !$('#tab-perception').classList.contains('active') || !pvS.d) { p3.last = 0; return; } const dt = p3.last ? Math.min(0.05, (now - p3.last) / 1000) : 0.016; p3.last = now; let moving = false;
  if (pv.dirty) { pvCompute(); pvCaption(); pvWhy(); pvReadout(); }
  if (pv.mode3d === true) { if (pv.dirty) pvUpdateMap3D(); moving = pvStepCamera(dt); pvUpdateActors3D(); pvNameLabels(pvProject3D); pvPlaceLabels(); p3.renderer.render(p3.scene, p3.camera); }
  else if (pv.mode3d === false) { if (!p2.P) pvResize2D(); if (p2.P) { pvDraw2D(); pvNameLabels(pvProject2D); pvPlaceLabels(); } }
  pv.dirty = false; if (moving || pvCam.dragging) p3.raf = requestAnimationFrame(pvTick); else p3.last = 0; }
function pvInvalidate(){ pv.dirty = true; pvRequest(); }
function pvStartRenderer(){ if (pv.mode3d !== null || pv.loading) return; const go2d = (why) => { pv.loading = false; pv.mode3d = false; pvInit2D(why); pvResize2D(); pvNote(); pvInvalidate(); }; if (pv.force2d) { go2d('the flat view was asked for with pv2d=1'); return; } const probe = document.createElement('canvas'); if (!(probe.getContext('webgl') || probe.getContext('experimental-webgl'))) { go2d('this browser has no WebGL'); return; }
  pv.loading = true; pvLoadThree(() => { pv.loading = false; if (pv.mode3d !== null) return; try { pvInit3D(); pv.mode3d = true; pvResize3D(); pvPreset(pv.cam, true); } catch (e) { console.error(e); if (p3.renderer) p3.renderer.domElement.remove(); go2d('the 3D view failed to start'); return; } pvNote(); pvInvalidate(); }, () => go2d('three.js could not be loaded')); }
function pvNote(){ pvEl.port.setAttribute('data-renderer', pv.mode3d ? '3d' : '2d'); if (pv.mode3d === false) { pvEl.empty.hidden = false; pvEl.empty.textContent = `Flat view: ${pv.why2d}. The layers are the same; heights are not drawn.`; } }

// ---- hooks called by replay.js ----
function pvRefresh(){ const on = rp.mode === 'perceived'; pv.on = on; pvEl.view.hidden = !on; $('#pLegend').hidden = on; if (!on) return; rpViews[0].fig.hidden = true; rpViews[1].fig.hidden = true;
  const ep = rpEps[rp.ep], d = pvData(rp.ep); $('#pLead').textContent = 'The same recorded attack, drawn as the map the observers built of the yard: what they have swept, what they believe is standing there, and where the patrol wants the drones next.';
  pvEl.bar.hidden = pvEl.port.hidden = pvEl.read.hidden = !d; pvEl.src.querySelectorAll('button').forEach(b => b.setAttribute('aria-pressed', String(b.dataset.src === pv.src))); $('#pvPrio').checked = pv.prio;
  if (!d) { pvEl.cap.innerHTML = `<b>${rpNames[rp.ep]}</b>`; pvEl.legend.innerHTML = ''; pvEl.why.innerHTML = ''; pvWhySig = ''; pvEl.empty.hidden = false; pvEl.empty.textContent = !ep ? `No recorded episode for "${rpNames[rp.ep].toLowerCase()}". ${RP_MISSING}` : `This page's data has no perceived map for the "${rpNames[rp.ep].toLowerCase()}" episode (episodes.${rp.ep}.view is empty). It is built only when the recording is a full position log, the fleet file matches the log and dimOS can be imported. With dimos installed in the environment, run: PYTHONPATH=$PWD/src .venv/bin/python pitch/build_app.py --tactics-dir results/v3/tactics`; return; }
  pvEl.empty.hidden = pv.mode3d !== false; pvS.d = d; pvS.ep = ep; pvCompute(); pvLegend(); pvStartRenderer(); if (pv.mode3d === true) pvResize3D(); else if (pv.mode3d === false) pvResize2D(); pvInvalidate(); }
function pvSync(){ if (!pv.on) return; const f = Math.floor(rp.t + 1e-6); if (f !== pv.frame || rp.ep !== pv.key) { pv.frame = f; pv.key = rp.ep; pv.dirty = true; } pvRequest(); }
pvEl.src = $('#pvSrc');
window.__perceived = {refresh: pvRefresh, sync: pvSync, state: pv, stats: () => ({renderer: pv.mode3d, frame: pvS.f, known: pvS.S && pvS.S.known, occupied: pvS.occ.length})};

// ---- controls ----
pvEl.src.addEventListener('click', e => { const b = e.target.closest('button[data-src]'); if (!b || b.dataset.src === pv.src) return; pv.src = b.dataset.src; pvEl.src.querySelectorAll('button').forEach(x => x.setAttribute('aria-pressed', String(x === b))); pvCompute(); pvLegend(); pvInvalidate(); });
$('#pvPrio').addEventListener('change', e => { pv.prio = e.target.checked; pvLegend(); pvInvalidate(); });
pvEl.hud.addEventListener('click', e => { const b = e.target.closest('button[data-cam]'); if (!b || pv.mode3d !== true) return; const c = b.dataset.cam; if (c === 'in') pvZoom(0.7); else if (c === 'out') pvZoom(1 / 0.7); else if (c === 'fit') { pvCam.fitted = true; pvCam.preset = ''; pvApplyFit(); pvSyncHud(); pvRequest(); } else pvPreset(c); });
// arrow keys move along a segmented control and choose, as in a radio group; the event stops here so the replay does not also step
function pvSegKeys(el){ el.addEventListener('keydown', e => { if (!['ArrowLeft', 'ArrowRight', 'Home', 'End'].includes(e.key)) return; const bs = [...el.querySelectorAll('button:not([disabled])')], i = bs.indexOf(document.activeElement); if (i < 0) return; e.preventDefault(); e.stopPropagation(); const j = e.key === 'Home' ? 0 : e.key === 'End' ? bs.length - 1 : (i + (e.key === 'ArrowRight' ? 1 : -1) + bs.length) % bs.length; bs[j].focus(); bs[j].click(); }); }
[$('#pMode'), $('#pEpSeg'), pvEl.src].forEach(pvSegKeys);
// pointers: drag orbits, shift or right button pans, two fingers pinch; one finger moving up or down scrolls the page (touch-action: pan-y)
const pvPtr = [{id: -1, x: 0, y: 0}, {id: -1, x: 0, y: 0}]; let pvPan = false, pvPinch = 0, pvMoved = 0;
const pvNPtr = () => (pvPtr[0].id >= 0 ? 1 : 0) + (pvPtr[1].id >= 0 ? 1 : 0);
const pvPick = (e) => { pv.hover = pv.mode3d === true ? pvPick3D(e.clientX, e.clientY) : pv.mode3d === false && p2.P ? pvPick2D(e.clientX, e.clientY) : null; pvReadout(); };
pvEl.port.addEventListener('pointerdown', e => { if (e.target.closest('.pv-hud')) return; const s = pvPtr[0].id < 0 ? pvPtr[0] : pvPtr[1].id < 0 ? pvPtr[1] : null; if (!s) return; s.id = e.pointerId; s.x = e.clientX; s.y = e.clientY; pvMoved = 0; pvPan = e.button === 2 || e.button === 1 || e.shiftKey; try { pvEl.port.setPointerCapture(e.pointerId); } catch (_) {} if (pvNPtr() === 2) pvPinch = Math.hypot(pvPtr[0].x - pvPtr[1].x, pvPtr[0].y - pvPtr[1].y); });
pvEl.port.addEventListener('pointermove', e => { const s = pvPtr[0].id === e.pointerId ? pvPtr[0] : pvPtr[1].id === e.pointerId ? pvPtr[1] : null; if (!s) { if (e.pointerType === 'mouse' && pvS.d) pvPick(e); return; } if (pv.mode3d !== true) return; const dx = e.clientX - s.x, dy = e.clientY - s.y; s.x = e.clientX; s.y = e.clientY; pvMoved += Math.abs(dx) + Math.abs(dy); const g = pvCam.goal;
  if (pvNPtr() === 2) { const dist = Math.hypot(pvPtr[0].x - pvPtr[1].x, pvPtr[0].y - pvPtr[1].y); if (pvPinch > 0 && dist > 0) pvZoom(pvPinch / dist, (pvPtr[0].x + pvPtr[1].x) / 2, (pvPtr[0].y + pvPtr[1].y) / 2); pvPinch = dist; }
  else if (pvPan) { const mpp = 2 * g.h / pvCam.viewH; pvShift(-dx * mpp, dy * mpp); pvCam.fitted = false; pvCam.preset = ''; }
  else { g.th += dx * 0.006; g.ph = Math.max(PV_PHI_MIN, Math.min(PV_PHI_MAX, g.ph - dy * 0.006)); pvCam.fitted = false; pvCam.preset = ''; }
  if (pvMoved > 4 && !pvCam.dragging) { pvCam.dragging = true; pvEl.port.classList.add('dragging'); } pvSyncHud(); pvRequest(); });
const pvUp = (e) => { let mine = false; for (const s of pvPtr) if (s.id === e.pointerId) { s.id = -1; mine = true; } if (!mine) return; if (pvMoved <= 4 && e.type === 'pointerup' && pvS.d) pvPick(e); if (pvNPtr() === 0) { pvCam.dragging = false; pvEl.port.classList.remove('dragging'); } };
pvEl.port.addEventListener('pointerup', pvUp); pvEl.port.addEventListener('pointercancel', pvUp);
pvEl.port.addEventListener('pointerleave', e => { if (e.pointerType === 'mouse' && pvNPtr() === 0) { pv.hover = null; pvReadout(); } });
pvEl.port.addEventListener('contextmenu', e => e.preventDefault());
pvEl.port.addEventListener('dblclick', e => { if (pv.mode3d === true && !e.target.closest('.pv-hud')) { pvCam.fitted = true; pvApplyFit(); pvRequest(); } });
pvEl.port.addEventListener('wheel', e => { if (pv.mode3d !== true || !(e.ctrlKey || e.metaKey)) return; e.preventDefault(); pvZoom(Math.exp(Math.max(-60, Math.min(60, e.deltaY)) * 0.01), e.clientX, e.clientY); }, {passive: false});
if (window.ResizeObserver) new ResizeObserver(() => { if (!pv.on) return; if (pv.mode3d === true) pvResize3D(); else if (pv.mode3d === false) pvResize2D(); pvInvalidate(); }).observe(pvEl.port);
function pvThemeChanged(){ pvTok = null; if (p3.ready) { const k = pvTokens(); for (const [m, tok] of p3.mats) m.color.set(k[tok]); p3.scene.background.set(k.ground); p3.hatch.image = pvHatch(); p3.hatch.needsUpdate = true; } if (pv.on) { pvLegend(); pvInvalidate(); } }
new MutationObserver(pvThemeChanged).observe(document.documentElement, {attributes: true, attributeFilter: ['data-theme']});
if (window.matchMedia) { const mq = window.matchMedia('(prefers-color-scheme: dark)'); if (mq.addEventListener) mq.addEventListener('change', pvThemeChanged); }

// ---- deep link: ?mode=perceived&ep=miss|catch&t=<s>&src=drones|swarm&prio=0|1&cam=top|angled ----
if (pvQ.get('mode') === 'perceived') { const ep = pvQ.get('ep'); if (rpEps[ep]) rp.ep = ep; rp.mode = 'perceived'; const t = parseFloat(pvQ.get('t')); if (!Number.isNaN(t)) { rp.opened = true; rp.t = Math.max(0, t); } rpRefresh(); } else pvRefresh();
