// ---------- perception: recorded replay, one clock for the plan views, the score chart and the event list ----------
// The payload carries no operating threshold (D.report has the false-alarm rate, not the score it maps to),
// so the chart draws this single reference value and says so.
const ALARM_THRESHOLD_REF = 4.0;
const RP_SPEEDS = [0.5, 1, 2, 4];
const RP_MISSING = 'Run pitch/make_clips.py, then pitch/build_app.py.';
const rpValid = (ep) => (ep && ep.tracks && Object.keys(ep.tracks).length && ep.t_end > 0) ? ep : null;
const rpEps = {miss: rpValid(missEp), catch: rpValid(catchEp)};
const rpNames = {miss: 'Before', catch: 'After'};
const rp = {t: 0, playing: false, speed: 2, mode: 'single', ep: rpEps.catch ? 'catch' : 'miss', opened: false, lastSent: 0, sec: -1, evIdx: -2};
const rpReduced = window.matchMedia ? window.matchMedia('(prefers-reduced-motion: reduce)') : {matches: false};
const rpViews = [
  {canvas: $('#pcanvas'), fig: $('#pViewA'), cap: $('#pCapA'), empty: $('#pEmptyA'), stat: document.createElement('canvas'), key: '', rects: []},
  {canvas: $('#pcanvas2'), fig: $('#pViewB'), cap: $('#pCapB'), empty: $('#pEmptyB'), stat: document.createElement('canvas'), key: '', rects: []},
];
const rpShown = () => rp.mode === 'compare' ? [['miss', rpViews[0]], ['catch', rpViews[1]]] : [[rp.ep, rpViews[0]]];
const rpFocusEp = () => rp.mode === 'compare' ? (rpEps.catch || rpEps.miss) : (rpEps[rp.ep] || rpEps.catch || rpEps.miss);
const rpEnd = () => Math.max(1, ...rpShown().map(([k]) => rpEps[k] ? rpEps[k].t_end : 0));
const rpName = (id) => id.replace(/^go2/, 'Go2').replaceAll('_', ' ');
const rpPlace = (s) => s.replaceAll('_', ' ');
const rpList = (a) => a.length < 2 ? a.join('') : a.slice(0, -1).join(', ') + ' and ' + a[a.length - 1];
const rpScoreAt = (ep, t) => { let v = null; for (const s of ep.scores) { if (s[0] <= t) v = s[1]; else break; } return v; };

// ---- colours: tokens only, re-read when the theme changes ----
let rpTok = null;
function rpTokens(){ if (rpTok) return rpTok; const cs = getComputedStyle(document.documentElement); const g = (n) => cs.getPropertyValue(n).trim(); rpTok = {ink: g('--ink'), ink2: g('--ink-2'), ink3: g('--ink-3'), surface: g('--surface'), grid: g('--grid'), fence: g('--fence'), asset: g('--asset'), drone: g('--fleet-drone'), go2: g('--fleet-go2'), guard: g('--fleet-guard'), camera: g('--fleet-camera'), intruder: g('--intruder'), benign: g('--benign'), alarm: g('--alarm')}; return rpTok; }
function rpThemeChanged(){ rpTok = null; rpViews.forEach(v => { v.key = ''; }); rpChart(); rpLegend(); rpDraw(); }
new MutationObserver(rpThemeChanged).observe(document.documentElement, {attributes: true, attributeFilter: ['data-theme']});
if (window.matchMedia) { const mq = window.matchMedia('(prefers-color-scheme: dark)'); if (mq.addEventListener) mq.addEventListener('change', rpThemeChanged); }

// ---- geometry: everything from site.bounds, drawn in CSS pixels on a devicePixelRatio-sized backing store ----
const RP_FONT = '500 11px Barlow, sans-serif';
const rpBW = site.bounds[2] - site.bounds[0], rpBH = site.bounds[3] - site.bounds[1];
function rpGeom(W, H){ const ML = 30, MR = 30, MT = 12, MB = 20; const s = Math.min((W - ML - MR) / rpBW, (H - MT - MB) / rpBH); const ox = ML + ((W - ML - MR) - rpBW * s) / 2, oy = MT + ((H - MT - MB) - rpBH * s) / 2; return {s, ML, MB, P: (x, y) => [ox + (x - site.bounds[0]) * s, oy + (site.bounds[3] - y) * s]}; }
function resizePerception(){ let changed = false; rpShown().forEach(([, v]) => { const c = v.canvas; if (c.hidden) return; const w = c.clientWidth; if (w < 10) return; const h = Math.round((w - 60) * rpBH / rpBW + 32); const dpr = Math.min(window.devicePixelRatio || 1, 3); c.style.height = h + 'px'; const bw = Math.round(w * dpr), bh = Math.round(h * dpr); if (c.width !== bw || c.height !== bh) { c.width = bw; c.height = bh; changed = true; } v.w = w; v.h = h; v.dpr = dpr; }); const sw = $('#spark').parentNode.clientWidth; if (sw > 10 && Math.abs(sw - rpChartW) > 1) rpChart(); rpDraw(); return changed; }

function rpLabel(g, text, x, y, r, taken, W, H, colour, halo){ const w = g.measureText(text).width, h = 12, d = r + 3; const cands = [[x + d, y - d - h + 4], [x + d, y + d - 4], [x - d - w, y - d - h + 4], [x - d - w, y + d - 4], [x - w / 2, y - d - h], [x - w / 2, y + d], [x - d - w, y - d - h - 12], [x - d - w, y + d + 10], [x + d, y - d - h - 12], [x + d, y + d + 10], [x - w / 2, y - d - h - 14], [x - w / 2, y + d + 14]]; const free = (c) => c[0] >= 2 && c[1] >= 2 && c[0] + w <= W - 2 && c[1] + h <= H - 2 && !taken.some(q => c[0] < q[0] + q[2] && q[0] < c[0] + w && c[1] < q[1] + q[3] && q[1] < c[1] + h); let c = cands.find(free); if (!c) { c = cands.find(q => q[0] >= 2 && q[1] >= 2 && q[0] + w <= W - 2 && q[1] + h <= H - 2) || [Math.max(2, Math.min(W - 2 - w, cands[0][0])), Math.max(2, Math.min(H - 2 - h, cands[0][1]))]; } taken.push([c[0], c[1], w, h]); g.textBaseline = 'top'; g.textAlign = 'left'; g.lineJoin = 'round'; g.lineWidth = 3; g.strokeStyle = halo; g.strokeText(text, c[0], c[1]); g.fillStyle = colour; g.fillText(text, c[0], c[1]); }
function rpShape(g, kind, x, y, r){ g.beginPath(); if (kind === 'go2') g.rect(x - r, y - r, 2 * r, 2 * r); else if (kind === 'guard') { g.moveTo(x, y - r * 1.25); g.lineTo(x + r * 1.15, y + r * 0.9); g.lineTo(x - r * 1.15, y + r * 0.9); g.closePath(); } else if (kind === 'intruder') { g.moveTo(x, y - r * 1.35); g.lineTo(x + r * 1.35, y); g.lineTo(x, y + r * 1.35); g.lineTo(x - r * 1.35, y); g.closePath(); } else g.arc(x, y, r, 0, 7); }

function rpStatic(v, ep){ const W = v.w, H = v.h, dpr = v.dpr, k = rpTokens(); const key = [W, H, dpr, k.surface, ep.entry].join('|'); if (key === v.key) return; v.key = key; v.stat.width = v.canvas.width; v.stat.height = v.canvas.height; const g = v.stat.getContext('2d'); g.setTransform(dpr, 0, 0, dpr, 0, 0); const {s, P} = rpGeom(W, H); const rects = []; v.rects = rects;
  g.fillStyle = k.surface; g.fillRect(0, 0, W, H);
  const step = 20 * s >= 28 ? 20 : 40; const [gx0, gy0] = P(site.bounds[0], site.bounds[1]), [gx1, gy1] = P(site.bounds[2], site.bounds[3]);
  g.font = RP_FONT; g.strokeStyle = k.grid; g.lineWidth = 1; g.fillStyle = k.ink3; g.textBaseline = 'top'; g.textAlign = 'center';
  for (let x = site.bounds[0]; x <= site.bounds[2] + 1e-6; x += 20) { const px = Math.round(P(x, 0)[0]) + 0.5; g.beginPath(); g.moveTo(px, gy1); g.lineTo(px, gy0); g.stroke(); if ((x - site.bounds[0]) % step === 0) g.fillText(x + step > site.bounds[2] ? `${x} m` : String(x), px, gy0 + 5); }
  g.textAlign = 'right'; g.textBaseline = 'middle';
  for (let y = site.bounds[1]; y <= site.bounds[3] + 1e-6; y += 20) { const py = Math.round(P(0, y)[1]) + 0.5; g.beginPath(); g.moveTo(gx0, py); g.lineTo(gx1, py); g.stroke(); if ((y - site.bounds[1]) % step === 0) g.fillText(String(y), gx0 - 6, py); }
  site.fixed_sensors.forEach(sn => { const c = D.curves[sn.sensor_type]; if (!c) return; const [x, y] = P(sn.position.x, sn.position.y); const a0 = -(sn.heading_deg + c.fov_deg / 2) * Math.PI / 180, a1 = -(sn.heading_deg - c.fov_deg / 2) * Math.PI / 180; g.beginPath(); g.moveTo(x, y); g.arc(x, y, c.range * s, a0, a1); g.closePath(); g.globalAlpha = 0.10; g.fillStyle = k.camera; g.fill(); g.globalAlpha = 0.7; g.strokeStyle = k.camera; g.lineWidth = 1; g.stroke(); g.globalAlpha = 1; g.fillStyle = k.camera; g.fillRect(x - 2.5, y - 2.5, 5, 5); });
  g.strokeStyle = k.fence; g.lineWidth = 2; g.beginPath(); site.perimeter.forEach((p, i) => { const [x, y] = P(p.x, p.y); i ? g.lineTo(x, y) : g.moveTo(x, y); }); g.closePath(); g.stroke();
  site.docks.forEach(d => { const [x, y] = P(d.position.x, d.position.y); g.strokeStyle = k.fence; g.lineWidth = 1.5; g.fillStyle = k.surface; g.beginPath(); g.arc(x, y, 6, 0, 7); g.fill(); g.stroke(); });
  site.entry_points.forEach(e => { const [x, y] = P(e.position.x, e.position.y); g.fillStyle = k.surface; g.strokeStyle = k.fence; g.lineWidth = 2; g.fillRect(x - 5, y - 5, 10, 10); g.strokeRect(x - 5, y - 5, 10, 10); });
  const [ax, ay] = P(site.asset.x, site.asset.y); g.fillStyle = k.asset; g.fillRect(ax - 6, ay - 6, 12, 12);
  rects.push([0, 0, 28, H], [0, H - 17, W, 17], [ax - 6, ay - 6, 12, 12]); v.slabels = [['asset', ax, ay, 6]];
  site.entry_points.forEach(e => { if (W < 520 && e.id !== ep.entry) return; const [x, y] = P(e.position.x, e.position.y); rects.push([x - 5, y - 5, 10, 10]); v.slabels.push([rpPlace(e.id), x, y, 6]); });
}

function rpDrawView(v, ep, epKey){ const W = v.w, H = v.h; if (!W || !H) return; rpStatic(v, ep); const g = v.canvas.getContext('2d'); g.setTransform(1, 0, 0, 1, 0, 0); g.drawImage(v.stat, 0, 0); g.setTransform(v.dpr, 0, 0, v.dpr, 0, 0); const k = rpTokens(), {s, P} = rpGeom(W, H), t = rp.t; const taken = v.rects.slice(); const labels = [];
  const ids = Object.keys(ep.tracks);
  // benign traffic, if the log recorded any
  ids.filter(id => kindOf(id) === 'benign' || kindOf(id) === 'decoy').forEach(id => { const tr = ep.tracks[id]; if (t < tr[0][0] || t > tr[tr.length - 1][0]) return; const p = positionAt(tr, t), [x, y] = P(p[1], p[2]); g.fillStyle = k.benign; g.beginPath(); g.arc(x, y, 3, 0, 7); g.fill(); });
  // sensor footprints first, faint, so the grid and the marks stay on top
  agentsOf(ep).forEach(id => { const kind = kindOf(id), p = positionAt(ep.tracks[id], t); if (isDocked(id, p[1], p[2])) return; const a = fleetAgents.find(z => z.id === id) || {}; const c = D.curves[a.sensor_type] || D.curves[kind === 'drone' ? 'drone_camera' : kind === 'go2' ? 'go2_camera' : 'human_eye']; if (!c) return; const [x, y] = P(p[1], p[2]); const col = k[kind] || k.drone; g.strokeStyle = col; g.fillStyle = col; g.lineWidth = 1; g.beginPath(); g.arc(x, y, c.range * s, 0, 7); g.globalAlpha = 0.45; g.setLineDash([3, 4]); g.stroke(); g.setLineDash([]); if (c.fov_deg >= 360) { g.globalAlpha = 0.07; g.fill(); } else { const q0 = positionAt(ep.tracks[id], t - 0.5), q1 = positionAt(ep.tracks[id], t + 0.5); const dx = q1[1] - q0[1], dy = q1[2] - q0[2]; if (Math.hypot(dx, dy) > 0.05) { const h = Math.atan2(-dy, dx), f = c.fov_deg * Math.PI / 360; g.beginPath(); g.moveTo(x, y); g.arc(x, y, c.range * s, h - f, h + f); g.closePath(); g.globalAlpha = 0.10; g.fill(); } } g.globalAlpha = 1; });
  // trails (last 40 s) and marks
  agentsOf(ep).forEach(id => { const kind = kindOf(id), tr = ep.tracks[id], col = k[kind] || k.drone; const p = positionAt(tr, t), [x, y] = P(p[1], p[2]); const docked = isDocked(id, p[1], p[2]); g.strokeStyle = col; g.globalAlpha = 0.55; g.lineWidth = 1.5; g.beginPath(); let st = false; for (const q of tr) { if (q[0] > t) break; if (q[0] < t - 40) continue; const [qx, qy] = P(q[1], q[2]); st ? g.lineTo(qx, qy) : g.moveTo(qx, qy); st = true; } if (st) { g.lineTo(x, y); g.stroke(); } g.globalAlpha = 1; rpShape(g, kind, x, y, 5); if (docked) { g.fillStyle = k.surface; g.fill(); g.strokeStyle = col; g.lineWidth = 2; g.stroke(); } else { g.fillStyle = col; g.fill(); } taken.push([x - 6, y - 6, 12, 12]); labels.push([rpName(id) + (docked ? ', docked' : ''), x, y, 6, k.ink]); });
  // intruder
  const itr = ep.tracks.intruder; let ix = null, iy = null;
  if (itr && t >= itr[0][0]) { const p = positionAt(itr, t); [ix, iy] = P(p[1], p[2]); g.strokeStyle = k.intruder; g.lineWidth = 2; g.beginPath(); let st = false; for (const q of itr) { if (q[0] > t) break; const [qx, qy] = P(q[1], q[2]); st ? g.lineTo(qx, qy) : g.moveTo(qx, qy); st = true; } g.lineTo(ix, iy); g.stroke(); rpShape(g, 'intruder', ix, iy, 5); g.fillStyle = k.intruder; g.fill(); taken.push([ix - 7, iy - 7, 14, 14]); const sc = rpScoreAt(ep, t); labels.unshift([sc == null ? 'intruder, not yet seen' : `intruder, score ${sc.toFixed(1)}`, ix, iy, 7, k.intruder]); }
  // looks in the last 1.5 s: a ring that opens on the object that was seen
  ep.detections.forEach(d => { if (d[0] > t || d[0] < t - 1.5 || !ep.tracks[d[2]]) return; const p = positionAt(ep.tracks[d[2]], t), [x, y] = P(p[1], p[2]); const o = positionAt(ep.tracks[d[1]] || ep.tracks[d[2]], t), [ox2, oy2] = P(o[1], o[2]); g.strokeStyle = d[3] ? k.intruder : k.benign; g.lineWidth = 1.5; g.globalAlpha = 1 - (t - d[0]) / 1.5; g.beginPath(); g.arc(x, y, 8 + 6 * (t - d[0]), 0, 7); g.stroke(); g.setLineDash([2, 3]); g.beginPath(); g.moveTo(ox2, oy2); g.lineTo(x, y); g.stroke(); g.setLineDash([]); g.globalAlpha = 1; });
  // alarm state: the only red on the plan, always with the word
  g.font = RP_FONT;
  if (ep.t_alarm != null && t >= ep.t_alarm) { if (ix != null) { g.strokeStyle = k.alarm; g.lineWidth = 2; g.beginPath(); g.arc(ix, iy, 12, 0, 7); g.stroke(); } const txt = `ALARM at ${ep.t_alarm.toFixed(0)} s, raised by ${rpName(ep.via || 'the fleet')}`; g.font = '600 12px Barlow, sans-serif'; const tw = g.measureText(txt).width; taken.push([34, 4, tw + 8, 16]); g.textBaseline = 'top'; g.textAlign = 'left'; g.lineWidth = 3; g.strokeStyle = k.surface; g.strokeText(txt, 38, 6); g.fillStyle = k.alarm; g.fillText(txt, 38, 6); g.font = RP_FONT; }
  labels.forEach(l => rpLabel(g, l[0], l[1], l[2], l[3], taken, W, H, l[4], k.surface)); v.slabels.forEach(l => rpLabel(g, l[0], l[1], l[2], l[3], taken, W, H, k.ink2, k.surface));
}
function rpDraw(){ if (rp.mode === 'perceived') return; rpShown().forEach(([key, v]) => { const ep = rpEps[key]; if (ep && !v.canvas.hidden) rpDrawView(v, ep, key); }); }

// ---- events in plain language, built from the episode ----
function rpDockedAtStart(ep){ return agentsOf(ep).filter(id => { const p = ep.tracks[id][0]; return isDocked(id, p[1], p[2]); }).map(id => { const tr = ep.tracks[id], p0 = tr[0]; const mv = tr.find(q => Math.hypot(q[1] - p0[1], q[2] - p0[2]) > 1); return {id, leaves: mv ? mv[0] : null}; }); }
function rpEventsOf(ep, key){ const ev = [], tag = rp.mode === 'compare' ? rpNames[key] : ''; const push = (t, text, cls) => ev.push({t: Math.max(0, Math.min(ep.t_end, t)), text, cls: cls || '', tag, key});
  push(0, `The intruder enters at the ${rpPlace(ep.entry)} (${rpPlace(ep.family)} tactic).`);
  const docked = rpDockedAtStart(ep); const stay = docked.filter(d => d.leaves == null), go = docked.filter(d => d.leaves != null);
  if (stay.length) push(0, `${rpList(stay.map(d => rpName(d.id)))} ${stay.length > 1 ? 'are' : 'is'} docked and charging at entry, and never ${stay.length > 1 ? 'leave' : 'leaves'} the dock in this recording.`);
  if (!docked.length) push(0, 'Every agent is out on patrol at entry; nobody is on a dock.');
  go.forEach(d => { push(0, `${rpName(d.id)} is docked and charging at entry.`); push(d.leaves, `${rpName(d.id)} leaves its dock.`); });
  const first = ep.detections.find(d => d[2] === 'intruder');
  if (first) push(first[0], `First detection of the intruder, by ${rpName(first[1])}, ${first[0].toFixed(0)} s after entry.`); else push(ep.t_cdp, 'Nobody has seen the intruder by this point, and nobody does.');
  const resp = site.response_time_s != null ? ` (the response takes ${site.response_time_s} s)` : '';
  push(ep.t_cdp, `Critical detection point, ${ep.t_cdp.toFixed(0)} s: the last moment a response still arrives in time${resp}.`);
  if (ep.t_alarm != null) { const m = ep.t_cdp - ep.t_alarm; push(ep.t_alarm, `Alarm delivered, ${ep.t_alarm.toFixed(0)} s after entry, ${m >= 0 ? `in time: ${m.toFixed(0)} s before the deadline` : `too late: ${(-m).toFixed(0)} s after the deadline`}${ep.via ? `. Raised by ${rpName(ep.via)}.` : '.'}`, 'alarm'); }
  const itr = ep.tracks.intruder, hit = itr && itr.find(q => Math.hypot(q[1] - site.asset.x, q[2] - site.asset.y) < 0.5), tReach = hit ? hit[0] : ep.t_end;
  if (ep.t_alarm == null || ep.t_alarm > ep.t_cdp) push(tReach, `${ep.t_alarm == null ? 'No alarm before the deadline: the' : 'The alarm came too late: the'} intruder reached the asset, ${tReach.toFixed(0)} s after entry.`); else push(tReach, `The intruder gets to the asset at ${tReach.toFixed(0)} s, but the alarm left enough time for the response to be there first.`);
  return ev; }
let rpEvents = [];
function rpBuildEvents(){ rpEvents = rpShown().flatMap(([key]) => rpEps[key] ? rpEventsOf(rpEps[key], key) : []).map((e, i) => ({...e, i})).sort((a, b) => (a.t - b.t) || (a.i - b.i)).reduce((acc, e) => { const same = acc.find(q => q.text === e.text && Math.abs(q.t - e.t) < 0.05); if (same) same.tag = 'Both'; else acc.push(e); return acc; }, []); $('#pEvents').innerHTML = rpEvents.length ? rpEvents.map((e, i) => `<li><button type="button" data-i="${i}" aria-current="false"><span class="when">${e.t.toFixed(0)} s</span><span>${e.tag ? `<span class="rp-tag">${e.tag}: </span>` : ''}<span class="${e.cls}">${esc(e.text)}</span></span></button></li>`).join('') : `<li class="empty">No recorded episode, so there are no events. ${RP_MISSING}</li>`; rp.evIdx = -2; }
function rpStepEvent(dir){ const times = [...new Set([0, ...rpEvents.map(e => +e.t.toFixed(2)), +rpEnd().toFixed(2)])].sort((a, b) => a - b); const nxt = dir > 0 ? times.find(x => x > rp.t + 0.05) : [...times].reverse().find(x => x < rp.t - 0.05); if (nxt != null) rpSeek(nxt, true); }

// ---- score chart ----
let rpChartW = 0, rpX = null;
function rpChart(){ const svg = $('#spark'), W = Math.max(280, Math.round(svg.parentNode.clientWidth - 18) || 360), H = 250, L = 34, R = 14, T = 70, B = 40; rpChartW = svg.parentNode.clientWidth; svg.setAttribute('viewBox', `0 0 ${W} ${H}`); svg.style.aspectRatio = `${W}/${H}`; const shown = rpShown().filter(([key]) => rpEps[key]); const note = $('#pChartNote');
  if (!shown.length) { svg.innerHTML = `<text x="${W / 2}" y="${H / 2}" text-anchor="middle">No recorded episode to chart.</text>`; note.textContent = RP_MISSING; rpX = null; return; }
  const tEnd = rpEnd(), vals = shown.flatMap(([key]) => rpEps[key].scores.map(s => s[1])); const lo = Math.min(-2, ...vals), hi = Math.max(ALARM_THRESHOLD_REF + 2, ...vals); const stepY = [1, 2, 5, 10, 20, 50].find(q => (hi - lo) / q <= 6) || 100; const ymin = Math.floor(lo / stepY) * stepY, ymax = Math.ceil(hi / stepY) * stepY; const X = (t) => L + t / tEnd * (W - L - R), Y = (v) => T + (1 - (v - ymin) / (ymax - ymin)) * (H - T - B); rpX = {X, L, R, W, tEnd};
  let s = `<text x="2" y="12" fill="var(--ink)" style="font-weight:600">Track score, log-likelihood ratio</text>`;
  for (let v = ymin; v <= ymax + 1e-9; v += stepY) s += `<line x1="${L}" x2="${W - R}" y1="${Y(v)}" y2="${Y(v)}" stroke="var(--grid)"/><text x="${L - 6}" y="${Y(v) + 4}" text-anchor="end">${v}</text>`;
  const stepX = (W - L - R) / (tEnd / 10) >= 34 ? 10 : 20; for (let t = 0; t <= tEnd; t += stepX) s += `<line x1="${X(t)}" x2="${X(t)}" y1="${H - B}" y2="${H - B + 4}" stroke="var(--ink-3)"/><text x="${X(t)}" y="${H - B + 16}" text-anchor="middle">${t}</text>`;
  s += `<line x1="${L}" x2="${W - R}" y1="${H - B}" y2="${H - B}" stroke="var(--ink-3)"/><text x="${(L + W - R) / 2}" y="${H - 6}" text-anchor="middle">Seconds since entry</text>`;
  const yT = Y(ALARM_THRESHOLD_REF); s += `<line x1="${L}" x2="${W - R}" y1="${yT}" y2="${yT}" stroke="var(--ink-2)" stroke-dasharray="5 4"/>`;
  const cdp = rpEps[shown[0][0]].t_cdp, xc = X(cdp); s += `<line x1="${xc}" x2="${xc}" y1="${T - 12}" y2="${H - B}" stroke="var(--ink-2)" stroke-dasharray="2 3"/>`;
  shown.forEach(([key]) => { const ep = rpEps[key], sc = ep.scores, before = rp.mode === 'compare' && key === 'miss'; if (!sc.length) return; s += `<path d="${sc.map((p, i) => `${i ? 'L' : 'M'}${X(p[0]).toFixed(1)},${Y(p[1]).toFixed(1)}`).join(' ')}" fill="none" stroke="var(${before ? '--ink-3' : '--ink'})" stroke-width="2" stroke-linejoin="round"${before ? ' stroke-dasharray="6 3"' : ''}/>`; sc.forEach(p => { s += `<circle cx="${X(p[0]).toFixed(1)}" cy="${Y(p[1]).toFixed(1)}" r="2.5" fill="var(${before ? '--ink-3' : '--ink'})"/>`; }); const last = sc[sc.length - 1]; if (rp.mode === 'compare') s += `<text class="halo" x="${X(last[0]) - 6}" y="${Y(last[1]) + 14}" text-anchor="end" fill="var(--ink)">${rpNames[key].toLowerCase()}</text>`; });
  s += `<text class="halo" x="${W - R - 2}" y="${yT - 5}" text-anchor="end">alarm fires above this line</text><text class="halo" x="${W - R - 2}" y="${yT + 13}" text-anchor="end">alarm threshold (reference ${ALARM_THRESHOLD_REF.toFixed(1)})</text>`;
  const cl = ['last moment a response still', `arrives in time, ${cdp.toFixed(0)} s`], cw = 150, xa0 = Math.max(0, ...shown.map(([key]) => rpEps[key].t_alarm != null && rpEps[key].t_alarm < cdp ? X(rpEps[key].t_alarm) : 0)), cx = Math.max(cw / 2 + 2, Math.min(W - cw / 2 - 2, Math.max(xc, xa0 ? xa0 + 8 + cw / 2 : 0))); s += `<text class="halo" x="${cx}" y="${T - 30}" text-anchor="middle">${cl[0]}</text><text class="halo" x="${cx}" y="${T - 17}" text-anchor="middle">${cl[1]}</text>`;
  shown.forEach(([key]) => { const ep = rpEps[key]; if (ep.t_alarm == null) return; const xa = X(ep.t_alarm), v = rpScoreAt(ep, ep.t_alarm); const left = xa > 110; s += `<line x1="${xa}" x2="${xa}" y1="${T - 40}" y2="${H - B}" stroke="var(--alarm)" stroke-width="1.5"/>${v == null ? '' : `<circle cx="${xa}" cy="${Y(v)}" r="6" fill="none" stroke="var(--alarm)" stroke-width="2"/>`}<text class="halo" x="${xa + (left ? -5 : 5)}" y="${T - 44}" text-anchor="${left ? 'end' : 'start'}" fill="var(--alarm)" style="font-weight:600">alarm${rp.mode === 'compare' ? ' (' + rpNames[key].toLowerCase() + ')' : ''}, ${ep.t_alarm.toFixed(0)} s</text>`; });
  s += `<g id="pPlayhead"><line x1="0" x2="0" y1="${T - 4}" y2="${H - B}" stroke="var(--ink)" stroke-width="1.5"/><path d="M-5,${T - 10} L5,${T - 10} L0,${T - 3} Z" fill="var(--ink)"/></g>`;
  svg.innerHTML = s; const empty = shown.filter(([key]) => !rpEps[key].scores.length).map(([key]) => rpNames[key].toLowerCase());
  note.textContent = (empty.length ? `No score line for the ${rpList(empty)} episode: no agent ever saw the intruder, so no track was scored. ` : '') + `The score rises each time an agent sees the intruder track. The threshold drawn is the reference value ${ALARM_THRESHOLD_REF.toFixed(1)}; this page's data does not carry the operating threshold. Click the chart to move the replay.`;
  rpPlayhead(); }
function rpPlayhead(){ const ph = document.getElementById('pPlayhead'); if (ph && rpX) ph.setAttribute('transform', `translate(${rpX.X(Math.min(rp.t, rpX.tEnd)).toFixed(1)},0)`); }
$('#spark').addEventListener('click', e => { if (!rpX) return; const r = $('#spark').getBoundingClientRect(); const x = (e.clientX - r.left) / r.width * rpX.W; rpSeek((x - rpX.L) / (rpX.W - rpX.L - rpX.R) * rpX.tEnd, true); });

// ---- captions, legend, agent cards, coverage ----
function rpOutcome(ep){ if (ep.t_alarm == null) return `missed: no alarm before the ${ep.t_cdp.toFixed(0)} s deadline, the intruder reached the asset`; const m = ep.t_cdp - ep.t_alarm; return m >= 0 ? `caught in time: alarm at ${ep.t_alarm.toFixed(0)} s, ${m.toFixed(0)} s before the ${ep.t_cdp.toFixed(0)} s deadline` : `too late: alarm at ${ep.t_alarm.toFixed(0)} s, ${(-m).toFixed(0)} s after the ${ep.t_cdp.toFixed(0)} s deadline`; }
function rpCaptions(){ rpShown().forEach(([key, v]) => { const ep = rpEps[key]; v.fig.hidden = false; v.canvas.hidden = !ep; v.empty.hidden = !!ep; if (!ep) { v.cap.innerHTML = `<b>${rpNames[key]}</b>`; v.empty.textContent = `No recorded episode for "${rpNames[key].toLowerCase()}" (episodes.${key} is missing from this page's data). ${RP_MISSING}`; return; } v.cap.innerHTML = `<b>${rpNames[key]}: ${esc(prettyFleet(ep.fleet))}.</b> Tactic ${esc(rpPlace(ep.family))} through the ${esc(rpPlace(ep.entry))} (${esc(ep.tactic)}), seed ${ep.seed}. Outcome: <b>${esc(rpOutcome(ep))}</b>.`; }); if (rp.mode !== 'compare') rpViews[1].fig.hidden = true; $('#pStage').classList.toggle('compare', rp.mode === 'compare'); }
function rpLegend(){ const sw = (inner) => `<svg viewBox="0 0 14 14" aria-hidden="true">${inner}</svg>`; $('#pLegend').innerHTML = [[sw('<circle cx="7" cy="7" r="5" fill="var(--fleet-drone)"/>'), 'drone'], [sw('<rect x="2" y="2" width="10" height="10" fill="var(--fleet-go2)"/>'), 'Go2 robot'], [sw('<path d="M7 1 L13 12 L1 12 Z" fill="var(--fleet-guard)"/>'), 'guard'], [sw('<circle cx="7" cy="7" r="4.5" fill="var(--surface)" stroke="var(--fleet-drone)" stroke-width="2"/>'), 'hollow mark: on its dock'], [sw('<path d="M7 0.5 L13.5 7 L7 13.5 L0.5 7 Z" fill="var(--intruder)"/>'), 'intruder and its path'], [sw('<circle cx="7" cy="7" r="6" fill="var(--fleet-drone)" fill-opacity=".12" stroke="var(--fleet-drone)" stroke-dasharray="2 2"/>'), 'how far an agent can see'], [sw('<path d="M1 12 L13 8 A12 12 0 0 0 8 1 Z" fill="var(--fleet-camera)" fill-opacity=".25" stroke="var(--fleet-camera)"/>'), 'fixed camera'], [sw('<rect x="2.5" y="2.5" width="9" height="9" fill="var(--surface)" stroke="var(--fence)" stroke-width="2"/>'), 'entry point'], [sw('<circle cx="7" cy="7" r="5" fill="var(--surface)" stroke="var(--fence)" stroke-width="1.5"/>'), 'dock'], [sw('<rect x="1" y="1" width="12" height="12" fill="var(--asset)"/>'), 'asset'], [sw('<circle cx="7" cy="7" r="5" fill="none" stroke="var(--alarm)" stroke-width="2"/>'), 'alarm fired']].map(([i, t]) => `<span>${i}${t}</span>`).join('') + `<span>Grid squares are 20 m; north is up.</span>`; }
let cardsSig = '', coverSig = '';
function renderAgentCards(){ const ep = rpFocusEp(); if (!ep) { $('#agentCards').innerHTML = `<div class="empty">No recorded episode. ${RP_MISSING}</div>`; $('#coverageList').innerHTML = ''; return; } const t = Math.floor(rp.t);
  const cardsHtml = agentsOf(ep).map(id => { const p = positionAt(ep.tracks[id], t); const a = fleetAgents.find(z => z.id === id) || {id, type: kindOf(id)}; const b = batteryAt(a, t); const docked = isDocked(id, p[1], p[2]); const seen = ep.detections.filter(d => d[1] === id && d[2] === 'intruder' && d[0] <= t).length; const zone = zoneOf(p[1], p[2]).replace(/^the /, ''); const power = (b && a.type !== 'guard' && !(a.charge_time_s <= 0)) ? `battery ${Math.round(b.frac * 100)}%${docked ? ', charging' : ''}` : (a.type === 'guard' ? 'on foot' : 'no battery model'); return `<div class="stat"><div class="v" style="font-size:var(--text-lg)">${esc(rpName(id))}</div><div class="k">${docked ? 'on its dock' : 'patrolling near the ' + esc(zone)}</div><div class="d flat">${power}, ${seen === 0 ? 'has not seen the intruder' : `${seen} look${seen === 1 ? '' : 's'} at the intruder`}</div></div>`; }).join(''); if (cardsHtml !== cardsSig) { cardsSig = cardsHtml; $('#agentCards').innerHTML = cardsHtml; }
  const coverHtml = memoryAt(ep, t).map(r => `<div class="row ${r.seen == null ? 'sev-high' : (r.stale > 30 ? 'sev-med' : 'sev-low')}"><div class="dot"></div><div><div class="t">${esc(r.name)}</div><div class="s">${r.seen == null ? 'not seen since entry' : 'last seen by ' + esc(rpName(r.by))}</div></div><div class="n">${r.seen == null ? 'never' : (r.stale < 1 ? 'now' : r.stale.toFixed(0) + ' s')}</div></div>`).join(''); if (coverHtml !== coverSig) { coverSig = coverHtml; $('#coverageList').innerHTML = coverHtml; } }

// ---- clock ----
function rpAnnounce(force){ const now = performance.now(); if (!force && now - rp.lastSent < 100) return; rp.lastSent = now; window.dispatchEvent(new CustomEvent('airtight:time', {detail: {t: rp.t, episode: rp.mode === 'compare' ? 'catch' : rp.ep, source: 'replay'}})); }
function rpSync(){ const end = rpEnd(); $('#pT').textContent = `${rp.t.toFixed(1)} s`; const sc = $('#pScrub'); sc.value = rp.t.toFixed(1); sc.setAttribute('aria-valuetext', `${rp.t.toFixed(0)} seconds since entry, of ${end.toFixed(0)}`); rpPlayhead(); rpDraw();
  let idx = -1; rpEvents.forEach((e, i) => { if (e.t <= rp.t + 0.05) idx = i; }); if (idx !== rp.evIdx) { rp.evIdx = idx; const cur = idx < 0 ? null : rpEvents[idx].t; $('#pEvents').querySelectorAll('button').forEach((b, i) => b.setAttribute('aria-current', String(cur != null && Math.abs(rpEvents[i].t - cur) < 0.05))); }
  const sec = Math.floor(rp.t); if (sec !== rp.sec) { rp.sec = sec; renderAgentCards(); } if (window.__perceived) window.__perceived.sync(); }
function rpSeek(t, announce){ rp.t = Math.max(0, Math.min(rpEnd(), +t || 0)); rpSync(); if (announce) rpAnnounce(true); }
function rpSetPlaying(on){ if (on && !rpShown().some(([key]) => rpEps[key])) on = false; if (on && rp.t >= rpEnd() - 0.05) rp.t = 0; rp.playing = on; const b = $('#pPlay'); b.textContent = on ? 'Pause' : 'Play'; b.setAttribute('aria-label', on ? 'Pause the replay' : (rp.t <= 0.05 ? 'Play the replay' : 'Play the replay from here')); if (on) startLoop(); }
let pRunning = false, plast = 0;
function perceptionLoop(now){ if (!rp.playing || !$('#tab-perception').classList.contains('active') || document.hidden) { pRunning = false; return; } const dt = Math.min(0.1, (now - plast) / 1000); plast = now; rp.t += dt * rp.speed; if (rp.t >= rpEnd()) { rp.t = rpEnd(); rpSync(); rpAnnounce(true); rpSetPlaying(false); pRunning = false; return; } rpSync(); rpAnnounce(false); requestAnimationFrame(perceptionLoop); }
function startLoop(){ if (pRunning) return; pRunning = true; plast = performance.now(); requestAnimationFrame(perceptionLoop); }
function startPerception(){ setTimeout(() => { if (rp.stale) { rp.stale = false; rpRefresh(); } resizePerception(); if (!rp.opened) { rp.opened = true; if (!rpReduced.matches) rpSetPlaying(true); } else if (rp.playing) startLoop(); }, 0); }
document.addEventListener('visibilitychange', () => { if (!document.hidden) { if (rp.playing && $('#tab-perception').classList.contains('active')) startLoop(); requestRender(); } });

// ---- mode, episode, controls ----
function rpRefresh(){ const end0 = rpEnd(); $('#pMode').querySelectorAll('button').forEach(b => b.setAttribute('aria-pressed', String(b.dataset.mode === rp.mode))); $('#pEpSeg').hidden = rp.mode === 'compare'; $('#pEpSeg').querySelectorAll('button').forEach(b => b.setAttribute('aria-pressed', String(b.dataset.ep === rp.ep))); const f = rpFocusEp(); $('#pLead').textContent = !f ? `No recorded episode. ${RP_MISSING}` : rp.mode === 'compare' ? `The same attack, same seed, twice: against the baseline fleet and against the fixed fleet. One clock drives both.` : `One recorded attack against ${prettyFleet(f.fleet)}. Switch to "Before and after" to see the same attack against both fleets.`; $('#pScrub').max = end0.toFixed(1); $('#pEnd').textContent = `of ${end0.toFixed(0)} s`; const any = !!f; ['#pPlay', '#pPrev', '#pNext', '#pScrub'].forEach(q => { $(q).disabled = !any; }); rpCaptions(); rpBuildEvents(); rp.t = Math.min(rp.t, end0); rp.sec = -1; cardsSig = ''; rpChart(); resizePerception(); if (window.__perceived) window.__perceived.refresh(); rpSync(); }
$('#pMode').addEventListener('click', e => { const b = e.target.closest('button[data-mode]'); if (!b || b.dataset.mode === rp.mode) return; rp.mode = b.dataset.mode; rpRefresh(); rpAnnounce(true); });
$('#pEpSeg').addEventListener('click', e => { const b = e.target.closest('button[data-ep]'); if (!b || b.dataset.ep === rp.ep) return; rp.ep = b.dataset.ep; rpRefresh(); rpAnnounce(true); });
$('#pSpeed').innerHTML = RP_SPEEDS.map(v => `<button type="button" data-speed="${v}" aria-pressed="${v === rp.speed}" aria-label="Playback speed ${v} times">${v}×</button>`).join('');
$('#pSpeed').addEventListener('click', e => { const b = e.target.closest('button[data-speed]'); if (!b) return; rp.speed = parseFloat(b.dataset.speed); $('#pSpeed').querySelectorAll('button').forEach(x => x.setAttribute('aria-pressed', String(x === b))); });
$('#pPlay').addEventListener('click', () => rpSetPlaying(!rp.playing));
$('#pPrev').addEventListener('click', () => { rpSetPlaying(false); rpStepEvent(-1); });
$('#pNext').addEventListener('click', () => { rpSetPlaying(false); rpStepEvent(1); });
$('#pScrub').setAttribute('aria-label', 'Replay time, seconds since entry');
$('#pScrub').addEventListener('input', e => { rpSetPlaying(false); rpSeek(parseFloat(e.target.value), true); });
$('#pEvents').addEventListener('click', e => { const b = e.target.closest('button[data-i]'); if (!b) return; rpSetPlaying(false); rpSeek(rpEvents[+b.dataset.i].t, true); });
$('#tab-perception').addEventListener('keydown', e => { if (e.altKey || e.ctrlKey || e.metaKey) return; const tag = e.target.tagName; if (e.key === ' ' || e.code === 'Space') { if (tag === 'BUTTON') return; e.preventDefault(); rpSetPlaying(!rp.playing); return; } if (e.key !== 'ArrowLeft' && e.key !== 'ArrowRight') return; e.preventDefault(); const dir = e.key === 'ArrowRight' ? 1 : -1; rpSetPlaying(false); if (e.shiftKey) rpSeek(rp.t + dir, true); else rpStepEvent(dir); });
window.addEventListener('airtight:time', e => { const d = e.detail || {}; if (d.source === 'replay' || typeof d.t !== 'number' || Number.isNaN(d.t)) return; const active = $('#tab-perception').classList.contains('active'); if (active && rp.playing) return; if (rp.mode !== 'compare' && rpEps[d.episode] && d.episode !== rp.ep) { rp.ep = d.episode; if (active) rpRefresh(); else rp.stale = true; } rp.t = Math.max(0, Math.min(rpEnd(), d.t)); if (active) rpSync(); else rp.stale = true; });
window.addEventListener('resize', () => { resizePerception(); });
if (window.ResizeObserver) new ResizeObserver(() => { if ($('#tab-perception').classList.contains('active')) resizePerception(); }).observe($('#pStage'));
rpLegend(); rpRefresh(); if (location.hash === '#perception') startPerception();
