// ---------- vulnerability map (three.js) ----------
const viewer = $('#viewer'); let renderer, scene, camera, threeOk = false, mapLoading = false, renderQueued = false;
const cx = (site.bounds[0]+site.bounds[2])/2, cz = (site.bounds[1]+site.bounds[3])/2;
const toV = (x,y,h) => new THREE.Vector3(x - cx, h, -(y - cz));
const HOME_VIEW = {theta: -1.15, phi: 0.62, r: 300, tx: 0, tz: 0};
let orbit = {...HOME_VIEW};
const layers = {sec: [], atk: [], labels: []}; let roundFilter = 'all';
function requestRender(){ if (!threeOk || renderQueued) return; renderQueued = true; requestAnimationFrame(() => { renderQueued = false; if (viewer.closest('.page').classList.contains('active')) renderer.render(scene, camera); }); }
function ensureMap(){ if (threeOk || mapLoading) return; mapLoading = true; const boot = () => { try { initScene(); applyMapFilter(); } catch(e) { viewer.insertAdjacentHTML('afterbegin', `<p class="empty">3D view unavailable: ${esc(e.message||e)}</p>`); } }; if (window.THREE) { boot(); return; } const sc = document.createElement('script'); sc.src = 'https://cdnjs.cloudflare.com/ajax/libs/three.js/r128/three.min.js'; sc.onload = boot; sc.onerror = () => { viewer.insertAdjacentHTML('afterbegin', '<p class="empty">3D view could not load.</p>'); }; document.head.appendChild(sc); }
function setCam(){ camera.position.set(orbit.tx + orbit.r*Math.sin(orbit.phi)*Math.cos(orbit.theta), orbit.r*Math.cos(orbit.phi), orbit.tz + orbit.r*Math.sin(orbit.phi)*Math.sin(orbit.theta)); camera.lookAt(orbit.tx, 0, orbit.tz); requestRender(); }
function tube(points, color, radius, opacity){ const curve = new THREE.CatmullRomCurve3(points); const g = new THREE.TubeGeometry(curve, Math.max(8, points.length*2), radius, 6, false); const m = new THREE.Mesh(g, new THREE.MeshLambertMaterial({color, transparent: opacity < 1, opacity})); return m; }
function label(text, x, y, h, color){ const c = document.createElement('canvas'); c.width = 128; c.height = 64; const ctx = c.getContext('2d'); ctx.fillStyle = color; ctx.beginPath(); ctx.roundRect ? ctx.roundRect(8, 8, 112, 48, 24) : ctx.rect(8,8,112,48); ctx.fill(); ctx.fillStyle = '#fff3e6'; ctx.font = 'bold 30px Barlow, sans-serif'; ctx.textAlign = 'center'; ctx.textBaseline = 'middle'; ctx.fillText(text, 64, 33); const tex = new THREE.CanvasTexture(c); const s = new THREE.Sprite(new THREE.SpriteMaterial({map: tex, depthTest: false})); s.scale.set(16, 8, 1); s.position.copy(toV(x, y, h)); return s; }
function initScene(){
  renderer = new THREE.WebGLRenderer({antialias:true, powerPreference:'low-power'}); renderer.setPixelRatio(Math.min(window.devicePixelRatio||1, 1.5));
  viewer.insertBefore(renderer.domElement, viewer.firstChild);
  const cs = getComputedStyle(document.documentElement); const dark = matchMedia('(prefers-color-scheme: dark)').matches && document.documentElement.dataset.theme !== 'light' || document.documentElement.dataset.theme === 'dark';
  scene = new THREE.Scene(); scene.background = new THREE.Color(cs.getPropertyValue('--surface').trim() || '#fff');
  camera = new THREE.PerspectiveCamera(42, 1, 1, 2500); setCam();
  scene.add(new THREE.HemisphereLight(0xffffff, 0x777777, dark ? 0.75 : 1.0)); const sun = new THREE.DirectionalLight(0xffffff, 0.55); sun.position.set(80,140,60); scene.add(sun);
  const w = site.bounds[2]-site.bounds[0], d = site.bounds[3]-site.bounds[1];
  const ground = new THREE.Mesh(new THREE.PlaneGeometry(w+40, d+40), new THREE.MeshLambertMaterial({color: dark ? 0x20243d : 0xf8eedf})); ground.rotation.x = -Math.PI/2; ground.position.y = -0.2; scene.add(ground);
  const yard = new THREE.Mesh(new THREE.PlaneGeometry(w, d), new THREE.MeshLambertMaterial({color: dark ? 0x2a2f4d : 0xefe2cf})); yard.rotation.x = -Math.PI/2; scene.add(yard);
  const fenceMat = new THREE.MeshLambertMaterial({color: dark ? 0x9a9db3 : 0x5d627f});
  const P = site.perimeter; for (let i=0;i<P.length;i++){ const a=P[i], b=P[(i+1)%P.length]; const len=Math.hypot(b.x-a.x,b.y-a.y); const m=new THREE.Mesh(new THREE.BoxGeometry(len,2.4,0.4), fenceMat); m.position.copy(toV((a.x+b.x)/2,(a.y+b.y)/2,1.2)); m.rotation.y = -Math.atan2(b.y-a.y, b.x-a.x); scene.add(m); }
  site.entry_points.forEach(e => { const g=new THREE.Mesh(new THREE.BoxGeometry(5,3.2,1.4), new THREE.MeshLambertMaterial({color:0x2b3157})); g.position.copy(toV(e.position.x,e.position.y,1.6)); scene.add(g); });
  site.docks.forEach(dk => { const m=new THREE.Mesh(new THREE.CylinderGeometry(3.4,3.4,0.6,20), new THREE.MeshLambertMaterial({color:0x8fbfbb})); m.position.copy(toV(dk.position.x,dk.position.y,0.3)); scene.add(m); });
  const asset = new THREE.Mesh(new THREE.BoxGeometry(9,7,9), new THREE.MeshLambertMaterial({color:0x2b3157})); asset.position.copy(toV(site.asset.x, site.asset.y, 3.5)); scene.add(asset);
  site.fixed_sensors.forEach(s => { const c=D.curves[s.sensor_type]||{fov_deg:60,range:30}; const wedge=new THREE.Mesh(new THREE.CircleGeometry(c.range, 24, THREE.MathUtils.degToRad(s.heading_deg - c.fov_deg/2), THREE.MathUtils.degToRad(c.fov_deg)), new THREE.MeshBasicMaterial({color:0x2b3157, transparent:true, opacity:0.12, side:THREE.DoubleSide})); wedge.rotation.x = -Math.PI/2; wedge.position.copy(toV(s.position.x,s.position.y,0.15)); scene.add(wedge); const pole=new THREE.Mesh(new THREE.CylinderGeometry(0.4,0.4,6,8), new THREE.MeshLambertMaterial({color:0x2b3157})); pole.position.copy(toV(s.position.x,s.position.y,3)); scene.add(pole); });
  // where the fleet patrolled: the fixed fleet's recorded tracks
  const blues = {drone: 0x2b3157, go2: 0x2e6f6b, guard: 0x5c6aa3};
  agentsOf(catchEp).forEach(id => { const tr = catchEp.tracks[id]; const pts = []; for (let i=0;i<tr.length;i+= Math.max(1, Math.floor(tr.length/60))) pts.push(toV(tr[i][1], tr[i][2], kindOf(id)==='drone' ? 8 : 1.0)); if (pts.length > 2) { const m = tube(pts, blues[kindOf(id)] || 0x2b3157, kindOf(id)==='drone' ? 0.9 : 0.7, 0.85); layers.sec.push(m); scene.add(m); } });
  // attack paths that still landed, one per round
  D.rounds.forEach(r => { if(!r.tactic || !r.tactic.path.length) return; const pts = [...r.tactic.path.map(p => toV(p[0], p[1], 1.2)), toV(site.asset.x, site.asset.y, 1.2)]; const m = tube(pts, 0xa07070, 1.1, 0.95); m.userData.round = r.k; layers.atk.push(m); scene.add(m); const disc = new THREE.Mesh(new THREE.CircleGeometry(6 + 6*(r.tactic.miss||0), 28), new THREE.MeshBasicMaterial({color:0xa07070, transparent:true, opacity:0.25 + 0.45*(r.tactic.miss||0), side:THREE.DoubleSide})); disc.rotation.x = -Math.PI/2; disc.position.copy(toV(r.tactic.path[0][0], r.tactic.path[0][1], 0.25)); disc.userData.round = r.k; layers.atk.push(disc); scene.add(disc); const lb = label('R' + r.k, r.tactic.path[0][0], r.tactic.path[0][1], 9, '#a07070'); lb.userData.round = r.k; layers.labels.push(lb); scene.add(lb); if (r.tactic.decoy) { const ring = new THREE.Mesh(new THREE.RingGeometry(2.4, 3.4, 24), new THREE.MeshBasicMaterial({color:0xbbb092, side:THREE.DoubleSide})); ring.rotation.x = -Math.PI/2; ring.position.copy(toV(r.tactic.decoy[0], r.tactic.decoy[1], 0.3)); ring.userData.round = r.k; layers.atk.push(ring); scene.add(ring); } });
  threeOk = true; resizeViewer(); requestRender();
}
function applyMapFilter(){ const on = (o) => roundFilter === 'all' || o.userData.round === roundFilter; layers.atk.forEach(o => o.visible = toggles.atk && on(o)); layers.labels.forEach(o => o.visible = toggles.atk && on(o)); layers.sec.forEach(o => o.visible = toggles.sec); requestRender(); }
const toggles = {sec: true, atk: true};
function resizeViewer(){ if(!renderer) return; const r = viewer.getBoundingClientRect(); if(r.width<10) return; renderer.setSize(r.width, r.height, false); camera.aspect = r.width/r.height; camera.updateProjectionMatrix(); requestRender(); }
window.addEventListener('resize', resizeViewer);
let drag = null, pinch = null;
viewer.addEventListener('pointerdown', e => { drag = {x:e.clientX, y:e.clientY, pan: e.shiftKey || e.button === 1}; viewer.setPointerCapture(e.pointerId); });
viewer.addEventListener('pointermove', e => { if(!drag) return; const dx = e.clientX-drag.x, dy = e.clientY-drag.y; drag.x = e.clientX; drag.y = e.clientY; if (drag.pan) { pan(dx, dy); } else { orbit.theta += dx*0.006; orbit.phi = Math.min(1.45, Math.max(0.2, orbit.phi - dy*0.006)); } setCam(); });
viewer.addEventListener('pointerup', () => { drag=null; }); viewer.addEventListener('pointercancel', () => { drag=null; });
viewer.addEventListener('dblclick', () => { orbit = {...HOME_VIEW}; setCam(); });
viewer.addEventListener('wheel', e => { e.preventDefault(); orbit.r = Math.min(600, Math.max(50, orbit.r * (1 + Math.sign(e.deltaY)*0.08))); setCam(); }, {passive:false});
function pan(dx, dy){ const k = orbit.r/600; const fx = Math.cos(orbit.theta), fz = Math.sin(orbit.theta); orbit.tx -= (dx * -fz + dy * fx) * k * 0.9; orbit.tz -= (dx * fx + dy * fz) * k * 0.9; orbit.tx = Math.max(-120, Math.min(120, orbit.tx)); orbit.tz = Math.max(-80, Math.min(80, orbit.tz)); }
viewer.addEventListener('touchstart', e => { if (e.touches.length === 2) { drag = null; pinch = {d: Math.hypot(e.touches[0].clientX-e.touches[1].clientX, e.touches[0].clientY-e.touches[1].clientY), x: (e.touches[0].clientX+e.touches[1].clientX)/2, y: (e.touches[0].clientY+e.touches[1].clientY)/2}; } }, {passive:true});
viewer.addEventListener('touchmove', e => { if(e.touches.length===2 && pinch){ const d=Math.hypot(e.touches[0].clientX-e.touches[1].clientX, e.touches[0].clientY-e.touches[1].clientY); const x=(e.touches[0].clientX+e.touches[1].clientX)/2, y=(e.touches[0].clientY+e.touches[1].clientY)/2; orbit.r = Math.min(600, Math.max(50, orbit.r * pinch.d/d)); pan(x-pinch.x, y-pinch.y); pinch = {d, x, y}; setCam(); } }, {passive:true});
viewer.addEventListener('touchend', () => { pinch=null; });
const rounds = D.rounds;
$('#mapLead').textContent = rounds.length ? `Blue is where ${prettyFleet(fixed.name)} actually patrolled in the recorded night. Red is the path the red team still landed on after each round of fixes.` : `Blue is where the fleet patrolled in the recorded night. Red paths appear once the attack, fix, re-attack rounds are on disk.`;
$('#roundSeg').innerHTML = `<button data-round="all" aria-pressed="true">All rounds</button>` + rounds.map(r => `<button data-round="${r.k}" aria-pressed="false">Round ${r.k}</button>`).join('') + `<button class="sec" data-layer="sec" aria-pressed="true">Fleet trails</button><button class="atk" data-layer="atk" aria-pressed="true">Attack paths</button>`;
$('#roundSeg').addEventListener('click', e => { const b = e.target.closest('button'); if(!b) return; if (b.dataset.round != null) { roundFilter = b.dataset.round === 'all' ? 'all' : parseInt(b.dataset.round); $('#roundSeg').querySelectorAll('button[data-round]').forEach(x => x.setAttribute('aria-pressed', x===b ? 'true' : 'false')); } else { toggles[b.dataset.layer] = !toggles[b.dataset.layer]; b.setAttribute('aria-pressed', String(toggles[b.dataset.layer])); } applyMapFilter(); });
$('#holeList').innerHTML = rounds.length ? rounds.map(r => { const t = r.tactic || {}; const miss = t.miss == null ? (1 - r.worst_pd) : t.miss; return `<div class="row ${miss >= 0.9 ? 'sev-high' : miss >= 0.5 ? 'sev-med' : 'sev-low'}" data-round="${r.k}"><div class="dot"></div><div><div class="t">Round ${r.k}: ${esc((r.worst_family||'').replaceAll('_',' '))} through the ${esc((t.entry||'?').replaceAll('_',' '))}</div><div class="s">${esc(prettyFleet(r.fleet))} at $${r.cost.toFixed(0)}/h${t.phase!=null ? `, enters at phase ${fmt(t.phase)} of the charge cycle` : ''}${r.worst_pd_schedule_blind != null ? `, ${pct(r.worst_pd_schedule_blind)} caught with the schedule hidden` : ''} → ${r.move ? 'fix: ' + r.move.replaceAll('_',' ') : 'budget reached'}</div></div><div class="n">${Math.round(miss*100)}%<span>still missed</span></div></div>`; }).join('') : D.threats.map(t => `<div class="row ${t.miss >= 0.9 ? 'sev-high' : t.miss >= 0.5 ? 'sev-med' : 'sev-low'}"><div class="dot"></div><div><div class="t">${esc(t.family.replaceAll('_',' '))} through the ${esc(t.entry.replaceAll('_',' '))}</div><div class="s">phase ${fmt(t.phase)} of the charge cycle at ${fmt(t.speed,1)} m/s, found by ${esc(t.origin)}</div></div><div class="n">${Math.round(t.miss*100)}%<span>missed</span></div></div>`).join('');
$('#holeList').addEventListener('click', e => { const row = e.target.closest('.row[data-round]'); if(!row) return; const r = rounds.find(x => x.k === parseInt(row.dataset.round)); if(!r || !r.tactic) return; orbit.tx = r.tactic.path[0][0] - cx; orbit.tz = -(r.tactic.path[0][1] - cz); orbit.r = 120; setCam(); roundFilter = r.k; $('#roundSeg').querySelectorAll('button[data-round]').forEach(x => x.setAttribute('aria-pressed', String(x.dataset.round == r.k))); applyMapFilter(); showTab('tab-map', true); });
if (location.hash === '#map') ensureMap();

