// ---------- perception (recorded, non-interactive) ----------
const pc = $('#pcanvas'); const pctx = pc.getContext('2d'); let pt = 0, plast = performance.now(), pRunning = false, pLastDraw = 0; const pep = catchEp;
$('#pLead').textContent = `${prettyFleet(pep.fleet)} · seed ${pep.seed}`; $('#pEnd').textContent = `${pep.t_end.toFixed(0)} s`;
function resizePerception(){ const r = pc.getBoundingClientRect(); if (r.width < 10) return; const dpr = Math.min(window.devicePixelRatio||1, 1.5); pc.width = Math.round(r.width*dpr); pc.height = Math.round(r.width*dpr*120/200); }
const PAD = 8; const P2 = (x,y) => [pc.width * (x - site.bounds[0] + PAD)/(site.bounds[2]-site.bounds[0] + 2*PAD), pc.height * (1 - (y - site.bounds[1] + PAD)/(site.bounds[3]-site.bounds[1] + 2*PAD))];
const scoreAt = (t) => { let v = null; for (const s of pep.scores) { if (s[0] <= t) v = s[1]; else break; } return v; };
const pstatic = document.createElement('canvas'); let pstaticKey = '';
function drawStatic(){ const W = pc.width, H = pc.height, s = W/200; const key = W + 'x' + H + document.documentElement.dataset.theme; if (key === pstaticKey) return; pstaticKey = key; pstatic.width = W; pstatic.height = H; const g = pstatic.getContext('2d'); const cs = getComputedStyle(document.documentElement); const ink = cs.getPropertyValue('--ink').trim(), hair = cs.getPropertyValue('--hair2').trim(), surf = cs.getPropertyValue('--surface').trim();
  g.fillStyle = surf; g.fillRect(0,0,W,H);
  g.strokeStyle = hair; g.lineWidth = 1; for (let x=0;x<=200;x+=20){ const [px]=P2(x,0); g.beginPath(); g.moveTo(px,0); g.lineTo(px,H); g.stroke(); } for (let y=0;y<=120;y+=20){ const [,py]=P2(0,y); g.beginPath(); g.moveTo(0,py); g.lineTo(W,py); g.stroke(); }
  g.strokeStyle = ink; g.lineWidth = 2*s; g.beginPath(); site.perimeter.forEach((p,i) => { const [x,y]=P2(p.x,p.y); i ? g.lineTo(x,y) : g.moveTo(x,y); }); g.closePath(); g.stroke();
  site.fixed_sensors.forEach(sn => { const c = D.curves[sn.sensor_type]||{fov_deg:60,range:30}; const [x,y]=P2(sn.position.x, sn.position.y); g.fillStyle = 'rgba(43,49,87,.12)'; g.beginPath(); g.moveTo(x,y); g.arc(x,y,c.range*s, -(sn.heading_deg + c.fov_deg/2)*Math.PI/180, -(sn.heading_deg - c.fov_deg/2)*Math.PI/180); g.closePath(); g.fill(); });
  site.docks.forEach(d => { const [x,y]=P2(d.position.x,d.position.y); g.fillStyle='rgba(46,111,107,.35)'; g.beginPath(); g.arc(x,y,4*s,0,7); g.fill(); });
  site.entry_points.forEach(e => { const [x,y]=P2(e.position.x,e.position.y); g.fillStyle = ink; g.fillRect(x-3*s,y-3*s,6*s,6*s); });
  const [ax,ay]=P2(site.asset.x, site.asset.y); g.fillStyle='#2b3157'; g.fillRect(ax-4*s,ay-4*s,8*s,8*s); }
let pSec = -1;
function drawPerception(){ const W = pc.width, H = pc.height, s = W/200; const cs = getComputedStyle(document.documentElement); const ink = cs.getPropertyValue('--ink').trim(), ink3 = cs.getPropertyValue('--ink3').trim();
  drawStatic(); pctx.drawImage(pstatic, 0, 0);
  if (false) { pctx.strokeStyle = ink; pctx.lineWidth = 1; for (let x=0;x<=200;x+=20){ const [px]=P2(x,0); pctx.beginPath(); pctx.moveTo(px,0); pctx.lineTo(px,H); pctx.stroke(); } for (let y=0;y<=120;y+=20){ const [,py]=P2(0,y); pctx.beginPath(); pctx.moveTo(0,py); pctx.lineTo(W,py); pctx.stroke(); }
  pctx.strokeStyle = ink; pctx.lineWidth = 2*s; pctx.beginPath(); site.perimeter.forEach((p,i) => { const [x,y]=P2(p.x,p.y); i ? pctx.lineTo(x,y) : pctx.moveTo(x,y); }); pctx.closePath(); pctx.stroke();
  site.fixed_sensors.forEach(sn => { const c = D.curves[sn.sensor_type]||{fov_deg:60,range:30}; const [x,y]=P2(sn.position.x, sn.position.y); pctx.fillStyle = 'rgba(43,49,87,.12)'; pctx.beginPath(); pctx.moveTo(x,y); pctx.arc(x,y,c.range*s, -(sn.heading_deg + c.fov_deg/2)*Math.PI/180, -(sn.heading_deg - c.fov_deg/2)*Math.PI/180); pctx.closePath(); pctx.fill(); });
  site.docks.forEach(d => { const [x,y]=P2(d.position.x,d.position.y); pctx.fillStyle='rgba(46,111,107,.35)'; pctx.beginPath(); pctx.arc(x,y,4*s,0,7); pctx.fill(); });
  site.entry_points.forEach(e => { const [x,y]=P2(e.position.x,e.position.y); pctx.fillStyle = ink; pctx.fillRect(x-3*s,y-3*s,6*s,6*s); });
  const [ax,ay]=P2(site.asset.x, site.asset.y); pctx.fillStyle='#2b3157'; pctx.fillRect(ax-4*s,ay-4*s,8*s,8*s); }
  agentsOf(pep).forEach(id => { const p = positionAt(pep.tracks[id], pt); const [x,y]=P2(p[1],p[2]); const a = fleetAgents.find(z=>z.id===id)||{}; const c = D.curves[a.sensor_type] || {range: kindOf(id)==='drone'?40:kindOf(id)==='go2'?30:60, fov_deg: 360}; const docked = isDocked(id,p[1],p[2]); if(!docked){ pctx.fillStyle = 'rgba(43,49,87,.10)'; pctx.beginPath(); pctx.arc(x,y,c.range*s,0,7); pctx.fill(); } const tr = pep.tracks[id]; pctx.strokeStyle='rgba(43,49,87,.5)'; pctx.lineWidth=1.5*s; pctx.beginPath(); let started=false; for(const q of tr){ if(q[0]>pt) break; if(q[0] < pt-40) continue; const [qx,qy]=P2(q[1],q[2]); started ? pctx.lineTo(qx,qy) : pctx.moveTo(qx,qy); started=true; } pctx.stroke(); pctx.fillStyle = docked ? '#8c8262' : '#2b3157'; pctx.beginPath(); pctx.arc(x,y,3.2*s,0,7); pctx.fill(); pctx.fillStyle = ink; pctx.font = `${Math.round(9*s)}px Barlow, sans-serif`; pctx.fillText(id.replace('_',' '), x+5*s, kindOf(id)==='drone' ? y-4*s : y+11*s); });
  const itr = pep.tracks.intruder; if (itr) { const p = positionAt(itr, pt); if (pt >= itr[0][0] && pt <= itr[itr.length-1][0] + 1) { const [x,y]=P2(p[1],p[2]); const sc = scoreAt(pt); const conf = sc==null ? 0 : Math.max(0, Math.min(1, (sc + 2)/6)); pctx.strokeStyle = `rgba(160,112,112,${0.35+0.6*conf})`; pctx.lineWidth = 1.5*s; pctx.beginPath(); let st=false; for(const q of itr){ if(q[0]>pt) break; const [qx,qy]=P2(q[1],q[2]); st ? pctx.lineTo(qx,qy) : pctx.moveTo(qx,qy); st=true; } pctx.stroke(); pctx.fillStyle = sc==null ? ink3 : `rgba(160,112,112,${0.45+0.55*conf})`; pctx.beginPath(); pctx.arc(x,y,3.6*s,0,7); pctx.fill(); pctx.fillStyle = ink; pctx.fillText(sc==null ? 'unknown object' : `track ${sc.toFixed(1)}`, x+5*s, y+10*s); } }
  pep.detections.filter(d => pt-1.5 <= d[0] && d[0] <= pt && pep.tracks[d[2]]).forEach(d => { const p = positionAt(pep.tracks[d[2]], pt); const [x,y]=P2(p[1],p[2]); pctx.strokeStyle = d[3] ? '#a07070' : '#bbb092'; pctx.lineWidth = 2*s; pctx.beginPath(); pctx.arc(x,y,(6 + 4*(pt-d[0]))*s,0,7); pctx.stroke(); });
  if (pep.t_alarm != null && pt >= pep.t_alarm) { pctx.fillStyle = '#a07070'; pctx.font = `bold ${Math.round(11*s)}px Barlow, sans-serif`; pctx.fillText(`ALARM ${pep.t_alarm.toFixed(0)} s via ${(pep.via||'').replace('_',' ')}`, 8*s, 14*s); }
  const sec = Math.floor(pt); if (sec !== pSec) { pSec = sec; $('#pT').textContent = `t = ${sec} s`; $('#pBar').style.width = `${(pt/pep.t_end*100).toFixed(0)}%`; }
}
function perceptionLoop(now){ if (!$('#tab-perception').classList.contains('active') || document.hidden) { pRunning = false; return; } const dt = Math.min(0.1, (now - plast)/1000); plast = now; pt += dt*2.5; if (pt > pep.t_end + 2) { pt = 0; } if (now - pLastDraw >= 32) { pLastDraw = now; drawPerception(); renderAgentCards(); } requestAnimationFrame(perceptionLoop); }
function startPerception(){ if (pRunning) return; pRunning = true; plast = performance.now(); requestAnimationFrame(perceptionLoop); }
document.addEventListener('visibilitychange', () => { if (!document.hidden) { startPerception(); requestRender(); } });
let cardsAt = -10, cardsSig = '', coverSig = '';
function renderAgentCards(){ if (Math.abs(pt - cardsAt) < 4) return; cardsAt = pt; const cardsHtml = agentsOf(pep).map(id => { const p = positionAt(pep.tracks[id], pt); const a = fleetAgents.find(z=>z.id===id)||{id, type:kindOf(id)}; const b = batteryAt(a, pt); const docked = isDocked(id,p[1],p[2]); const seen = pep.detections.filter(d => d[1]===id && d[0] <= pt); return `<div class="stat"><div class="v" style="font-size:17px">${esc(id.replace('_',' '))}</div><div class="k">${docked ? 'charging at the dock' : 'patrolling near the ' + esc(zoneOf(p[1],p[2]))}</div><div class="d ${docked ? 'flat' : 'up'}">${b ? (docked ? (b.flying ? 'topping up' : 'charge ' + Math.round(b.frac*100) + '%') : (b.flying ? 'battery ' + Math.round(b.frac*100) + '%' : 'airborne')) : (a.type==='guard' ? 'on foot' : 'ground robot')} · ${seen.length} look${seen.length===1?'':'s'} on the track</div></div>`; }).join(''); if (cardsHtml !== cardsSig) { cardsSig = cardsHtml; $('#agentCards').innerHTML = cardsHtml; } const rows = memoryAt(pep, pt); const coverHtml = rows.slice(0,6).map(r => `<div class="row ${r.seen==null ? 'sev-high' : (r.stale > 30 ? 'sev-med' : 'sev-low')}"><div class="dot"></div><div><div class="t">${esc(r.name)}</div><div class="s">${r.seen==null ? 'not seen yet' : 'by ' + esc(r.by.replace('_',' '))}</div></div><div class="n">${r.seen==null ? '—' : r.stale.toFixed(0) + ' s'}<span>ago</span></div></div>`).join(''); if (coverHtml !== coverSig) { coverSig = coverHtml; $('#coverageList').innerHTML = coverHtml; } }
(function(){ const W=360,H=120,L=30,R=12,T=12,B=22; const sc = pep.scores; if(!sc.length){ $('#spark').innerHTML = `<text x="${W/2}" y="${H/2}" text-anchor="middle">no score series in this log</text>`; return; } const vals = sc.map(s=>s[1]); const ymin = Math.min(-2, ...vals), ymax = Math.max(5, ...vals); const X = (t) => L + t/pep.t_end*(W-L-R), Y = (v) => T + (1-(v-ymin)/(ymax-ymin))*(H-T-B); let s = `<line x1="${L}" x2="${W-R}" y1="${Y(4)}" y2="${Y(4)}" stroke="var(--atk)" stroke-dasharray="4 4" opacity=".7"/><text x="${W-R}" y="${Y(4)-4}" text-anchor="end">alarm at 4.0</text>`; s += `<path d="${sc.map((p,i)=>`${i?'L':'M'}${X(p[0]).toFixed(1)},${Y(p[1]).toFixed(1)}`).join(' ')}" fill="none" stroke="var(--brand)" stroke-width="2.2" stroke-linejoin="round"/>`; sc.forEach(p => { s += `<circle cx="${X(p[0])}" cy="${Y(p[1])}" r="3" fill="var(--brand)"/>`; }); if (pep.t_alarm != null) s += `<line x1="${X(pep.t_alarm)}" x2="${X(pep.t_alarm)}" y1="${T}" y2="${H-B}" stroke="var(--atk)" stroke-width="1.5"/>`; s += `<line x1="${X(pep.t_cdp)}" x2="${X(pep.t_cdp)}" y1="${T}" y2="${H-B}" stroke="var(--ink3)" stroke-dasharray="3 3"/><text x="${X(pep.t_cdp)}" y="${H-6}" text-anchor="middle">deadline ${pep.t_cdp.toFixed(0)} s</text><text x="${L}" y="${H-6}">0 s</text><text x="${L-6}" y="${Y(ymax)+4}" text-anchor="end">${ymax.toFixed(0)}</text><text x="${L-6}" y="${Y(ymin)+4}" text-anchor="end">${ymin.toFixed(0)}</text>`; $('#spark').innerHTML = s; })();
resizePerception(); drawPerception(); renderAgentCards(); if (location.hash === '#perception') startPerception(); window.addEventListener('resize', () => { resizePerception(); pstaticKey = ''; drawPerception(); });

